// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/config/accesslog/v2/als.proto

package v2

import (
	fmt "fmt"
	core "github.com/envoyproxy/go-control-plane/envoy/api/v2/core"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Configuration for the built-in *envoy.http_grpc_access_log*
// :ref:`AccessLog <envoy_api_msg_config.filter.accesslog.v2.AccessLog>`. This configuration will
// populate :ref:`StreamAccessLogsMessage.http_logs
// <envoy_api_field_service.accesslog.v2.StreamAccessLogsMessage.http_logs>`.
type HttpGrpcAccessLogConfig struct {
	CommonConfig *CommonGrpcAccessLogConfig `protobuf:"bytes,1,opt,name=common_config,json=commonConfig,proto3" json:"common_config,omitempty"`
	// Additional request headers to log in :ref:`HTTPRequestProperties.request_headers
	// <envoy_api_field_data.accesslog.v2.HTTPRequestProperties.request_headers>`.
	AdditionalRequestHeadersToLog []string `protobuf:"bytes,2,rep,name=additional_request_headers_to_log,json=additionalRequestHeadersToLog,proto3" json:"additional_request_headers_to_log,omitempty"`
	// Additional response headers to log in :ref:`HTTPResponseProperties.response_headers
	// <envoy_api_field_data.accesslog.v2.HTTPResponseProperties.response_headers>`.
	AdditionalResponseHeadersToLog []string `protobuf:"bytes,3,rep,name=additional_response_headers_to_log,json=additionalResponseHeadersToLog,proto3" json:"additional_response_headers_to_log,omitempty"`
	// Additional response trailers to log in :ref:`HTTPResponseProperties.response_trailers
	// <envoy_api_field_data.accesslog.v2.HTTPResponseProperties.response_trailers>`.
	AdditionalResponseTrailersToLog []string `protobuf:"bytes,4,rep,name=additional_response_trailers_to_log,json=additionalResponseTrailersToLog,proto3" json:"additional_response_trailers_to_log,omitempty"`
	XXX_NoUnkeyedLiteral            struct{} `json:"-"`
	XXX_unrecognized                []byte   `json:"-"`
	XXX_sizecache                   int32    `json:"-"`
}

func (m *HttpGrpcAccessLogConfig) Reset()         { *m = HttpGrpcAccessLogConfig{} }
func (m *HttpGrpcAccessLogConfig) String() string { return proto.CompactTextString(m) }
func (*HttpGrpcAccessLogConfig) ProtoMessage()    {}
func (*HttpGrpcAccessLogConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7b431652a309a2e, []int{0}
}

func (m *HttpGrpcAccessLogConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpGrpcAccessLogConfig.Unmarshal(m, b)
}
func (m *HttpGrpcAccessLogConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpGrpcAccessLogConfig.Marshal(b, m, deterministic)
}
func (m *HttpGrpcAccessLogConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpGrpcAccessLogConfig.Merge(m, src)
}
func (m *HttpGrpcAccessLogConfig) XXX_Size() int {
	return xxx_messageInfo_HttpGrpcAccessLogConfig.Size(m)
}
func (m *HttpGrpcAccessLogConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpGrpcAccessLogConfig.DiscardUnknown(m)
}

var xxx_messageInfo_HttpGrpcAccessLogConfig proto.InternalMessageInfo

func (m *HttpGrpcAccessLogConfig) GetCommonConfig() *CommonGrpcAccessLogConfig {
	if m != nil {
		return m.CommonConfig
	}
	return nil
}

func (m *HttpGrpcAccessLogConfig) GetAdditionalRequestHeadersToLog() []string {
	if m != nil {
		return m.AdditionalRequestHeadersToLog
	}
	return nil
}

func (m *HttpGrpcAccessLogConfig) GetAdditionalResponseHeadersToLog() []string {
	if m != nil {
		return m.AdditionalResponseHeadersToLog
	}
	return nil
}

func (m *HttpGrpcAccessLogConfig) GetAdditionalResponseTrailersToLog() []string {
	if m != nil {
		return m.AdditionalResponseTrailersToLog
	}
	return nil
}

// Configuration for the built-in *envoy.tcp_grpc_access_log* type. This configuration will
// populate *StreamAccessLogsMessage.tcp_logs*.
// [#not-implemented-hide:]
type TcpGrpcAccessLogConfig struct {
	CommonConfig         *CommonGrpcAccessLogConfig `protobuf:"bytes,1,opt,name=common_config,json=commonConfig,proto3" json:"common_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *TcpGrpcAccessLogConfig) Reset()         { *m = TcpGrpcAccessLogConfig{} }
func (m *TcpGrpcAccessLogConfig) String() string { return proto.CompactTextString(m) }
func (*TcpGrpcAccessLogConfig) ProtoMessage()    {}
func (*TcpGrpcAccessLogConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7b431652a309a2e, []int{1}
}

func (m *TcpGrpcAccessLogConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TcpGrpcAccessLogConfig.Unmarshal(m, b)
}
func (m *TcpGrpcAccessLogConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TcpGrpcAccessLogConfig.Marshal(b, m, deterministic)
}
func (m *TcpGrpcAccessLogConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TcpGrpcAccessLogConfig.Merge(m, src)
}
func (m *TcpGrpcAccessLogConfig) XXX_Size() int {
	return xxx_messageInfo_TcpGrpcAccessLogConfig.Size(m)
}
func (m *TcpGrpcAccessLogConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TcpGrpcAccessLogConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TcpGrpcAccessLogConfig proto.InternalMessageInfo

func (m *TcpGrpcAccessLogConfig) GetCommonConfig() *CommonGrpcAccessLogConfig {
	if m != nil {
		return m.CommonConfig
	}
	return nil
}

// Common configuration for gRPC access logs.
type CommonGrpcAccessLogConfig struct {
	// The friendly name of the access log to be returned in :ref:`StreamAccessLogsMessage.Identifier
	// <envoy_api_msg_service.accesslog.v2.StreamAccessLogsMessage.Identifier>`. This allows the
	// access log server to differentiate between different access logs coming from the same Envoy.
	LogName string `protobuf:"bytes,1,opt,name=log_name,json=logName,proto3" json:"log_name,omitempty"`
	// The gRPC service for the access log service.
	GrpcService *core.GrpcService `protobuf:"bytes,2,opt,name=grpc_service,json=grpcService,proto3" json:"grpc_service,omitempty"`
	// Interval for flushing access logs to the gRPC stream. Logger will flush requests every time
	// this interval is elapsed, or when batch size limit is hit, whichever comes first. Defaults to
	// 1 second.
	BufferFlushInterval *duration.Duration `protobuf:"bytes,3,opt,name=buffer_flush_interval,json=bufferFlushInterval,proto3" json:"buffer_flush_interval,omitempty"`
	// Soft size limit in bytes for access log entries buffer. Logger will buffer requests until
	// this limit it hit, or every time flush interval is elapsed, whichever comes first. Setting it
	// to zero effectively disables the batching. Defaults to 16384.
	BufferSizeBytes      *wrappers.UInt32Value `protobuf:"bytes,4,opt,name=buffer_size_bytes,json=bufferSizeBytes,proto3" json:"buffer_size_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CommonGrpcAccessLogConfig) Reset()         { *m = CommonGrpcAccessLogConfig{} }
func (m *CommonGrpcAccessLogConfig) String() string { return proto.CompactTextString(m) }
func (*CommonGrpcAccessLogConfig) ProtoMessage()    {}
func (*CommonGrpcAccessLogConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7b431652a309a2e, []int{2}
}

func (m *CommonGrpcAccessLogConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonGrpcAccessLogConfig.Unmarshal(m, b)
}
func (m *CommonGrpcAccessLogConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonGrpcAccessLogConfig.Marshal(b, m, deterministic)
}
func (m *CommonGrpcAccessLogConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonGrpcAccessLogConfig.Merge(m, src)
}
func (m *CommonGrpcAccessLogConfig) XXX_Size() int {
	return xxx_messageInfo_CommonGrpcAccessLogConfig.Size(m)
}
func (m *CommonGrpcAccessLogConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonGrpcAccessLogConfig.DiscardUnknown(m)
}

var xxx_messageInfo_CommonGrpcAccessLogConfig proto.InternalMessageInfo

func (m *CommonGrpcAccessLogConfig) GetLogName() string {
	if m != nil {
		return m.LogName
	}
	return ""
}

func (m *CommonGrpcAccessLogConfig) GetGrpcService() *core.GrpcService {
	if m != nil {
		return m.GrpcService
	}
	return nil
}

func (m *CommonGrpcAccessLogConfig) GetBufferFlushInterval() *duration.Duration {
	if m != nil {
		return m.BufferFlushInterval
	}
	return nil
}

func (m *CommonGrpcAccessLogConfig) GetBufferSizeBytes() *wrappers.UInt32Value {
	if m != nil {
		return m.BufferSizeBytes
	}
	return nil
}

func init() {
	proto.RegisterType((*HttpGrpcAccessLogConfig)(nil), "envoy.config.accesslog.v2.HttpGrpcAccessLogConfig")
	proto.RegisterType((*TcpGrpcAccessLogConfig)(nil), "envoy.config.accesslog.v2.TcpGrpcAccessLogConfig")
	proto.RegisterType((*CommonGrpcAccessLogConfig)(nil), "envoy.config.accesslog.v2.CommonGrpcAccessLogConfig")
}

func init() {
	proto.RegisterFile("envoy/config/accesslog/v2/als.proto", fileDescriptor_e7b431652a309a2e)
}

var fileDescriptor_e7b431652a309a2e = []byte{
	// 512 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x92, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xb1, 0x53, 0xa0, 0xd9, 0x16, 0x01, 0x46, 0xd0, 0x24, 0x82, 0x10, 0xd2, 0x4a, 0x54,
	0x1c, 0x6c, 0x29, 0xe5, 0xc2, 0xb1, 0x29, 0x82, 0x14, 0x05, 0x54, 0xb9, 0x01, 0x09, 0x2e, 0xd6,
	0xc6, 0x99, 0x6c, 0x57, 0xda, 0x78, 0x96, 0xdd, 0xb5, 0x21, 0xbd, 0x70, 0xe7, 0x51, 0xb8, 0x73,
	0xe1, 0xc4, 0xc3, 0x70, 0xe1, 0x2d, 0x90, 0x77, 0x5d, 0x9a, 0xd0, 0xe6, 0xcc, 0xcd, 0xd6, 0x7c,
	0xf3, 0xcd, 0x3f, 0xf6, 0x90, 0x6d, 0xc8, 0x0a, 0x9c, 0x47, 0x29, 0x66, 0x53, 0xce, 0x22, 0x9a,
	0xa6, 0xa0, 0xb5, 0x40, 0x16, 0x15, 0xbd, 0x88, 0x0a, 0x1d, 0x4a, 0x85, 0x06, 0x83, 0xa6, 0x85,
	0x42, 0x07, 0x85, 0x7f, 0xa1, 0xb0, 0xe8, 0xb5, 0x76, 0x5c, 0x3f, 0x95, 0xbc, 0x6c, 0x49, 0x51,
	0x41, 0xc4, 0x94, 0x4c, 0x13, 0x0d, 0xaa, 0xe0, 0x29, 0x38, 0x41, 0xab, 0xcd, 0x10, 0x99, 0x80,
	0xc8, 0xbe, 0x8d, 0xf3, 0x69, 0x34, 0xc9, 0x15, 0x35, 0x1c, 0xb3, 0x55, 0xf5, 0x4f, 0x8a, 0x4a,
	0x09, 0xaa, 0x0a, 0xd0, 0xda, 0x2a, 0xa8, 0xe0, 0x13, 0x6a, 0x20, 0x3a, 0x7b, 0x70, 0x85, 0xee,
	0x2f, 0x9f, 0x6c, 0x0d, 0x8c, 0x91, 0x2f, 0x95, 0x4c, 0xf7, 0x6d, 0xae, 0x21, 0xb2, 0x03, 0x9b,
	0x33, 0x00, 0x72, 0x23, 0xc5, 0xd9, 0x0c, 0xb3, 0xc4, 0x05, 0x6f, 0x78, 0x1d, 0x6f, 0x77, 0xa3,
	0xf7, 0x34, 0x5c, 0xb9, 0x4d, 0x78, 0x60, 0xf9, 0x4b, 0x64, 0x7d, 0xf2, 0xe3, 0xf7, 0xcf, 0xda,
	0xd5, 0xaf, 0x9e, 0x7f, 0xcb, 0x8b, 0x37, 0x9d, 0xb6, 0x1a, 0x33, 0x20, 0x8f, 0xe8, 0x64, 0xc2,
	0xcb, 0x6d, 0xa8, 0x48, 0x14, 0x7c, 0xcc, 0x41, 0x9b, 0xe4, 0x04, 0xe8, 0x04, 0x94, 0x4e, 0x0c,
	0x26, 0x02, 0x59, 0xc3, 0xef, 0xd4, 0x76, 0xeb, 0xf1, 0x83, 0x73, 0x30, 0x76, 0xdc, 0xc0, 0x61,
	0x23, 0x1c, 0x22, 0x0b, 0x5e, 0x91, 0xee, 0x92, 0x49, 0x4b, 0xcc, 0x34, 0xfc, 0xab, 0xaa, 0x59,
	0x55, 0x7b, 0x51, 0xe5, 0xc0, 0x25, 0xd7, 0x90, 0x6c, 0x5f, 0xe6, 0x32, 0x8a, 0x72, 0xb1, 0x20,
	0x5b, 0xb3, 0xb2, 0x87, 0x17, 0x65, 0xa3, 0x0a, 0xb4, 0xb6, 0xee, 0x17, 0x72, 0x6f, 0x94, 0xfe,
	0xc7, 0x8f, 0xdc, 0xfd, 0xee, 0x93, 0xe6, 0xca, 0xbe, 0x60, 0x87, 0xac, 0x0b, 0x64, 0x49, 0x46,
	0x67, 0x60, 0xe7, 0xd7, 0xfb, 0xf5, 0xd2, 0xb4, 0xa6, 0xfc, 0x8e, 0x17, 0x5f, 0x17, 0xc8, 0xde,
	0xd0, 0x19, 0x04, 0xaf, 0xc9, 0xe6, 0xe2, 0x69, 0x36, 0x7c, 0x9b, 0xb4, 0x5d, 0x25, 0xa5, 0x92,
	0x97, 0xe1, 0xca, 0x0b, 0x0e, 0xcb, 0x19, 0xc7, 0x8e, 0x5a, 0xca, 0xb4, 0xc1, 0xce, 0x0b, 0xc1,
	0x7b, 0x72, 0x77, 0x9c, 0x4f, 0xa7, 0xa0, 0x92, 0xa9, 0xc8, 0xf5, 0x49, 0xc2, 0x33, 0x03, 0xaa,
	0xa0, 0xa2, 0x51, 0xb3, 0xde, 0x66, 0xe8, 0x6e, 0x3a, 0x3c, 0xbb, 0xe9, 0xf0, 0x79, 0x75, 0xf3,
	0x95, 0xf2, 0x9b, 0xe7, 0x3f, 0xb9, 0x12, 0xdf, 0x71, 0x8e, 0x17, 0xa5, 0xe2, 0xb0, 0x32, 0x04,
	0x03, 0x72, 0xbb, 0x52, 0x6b, 0x7e, 0x0a, 0xc9, 0x78, 0x6e, 0x40, 0x37, 0xd6, 0xac, 0xf6, 0xfe,
	0x05, 0xed, 0xdb, 0xc3, 0xcc, 0xec, 0xf5, 0xde, 0x51, 0x91, 0x43, 0x7c, 0xd3, 0xb5, 0x1d, 0xf3,
	0x53, 0xe8, 0x97, 0x4d, 0xfd, 0x67, 0xe4, 0x31, 0x47, 0xb7, 0xa1, 0x54, 0xf8, 0x79, 0xbe, 0xfa,
	0xb7, 0xf4, 0xd7, 0xf7, 0x85, 0x3e, 0x2a, 0xa5, 0x47, 0xde, 0x07, 0xbf, 0xe8, 0x8d, 0xaf, 0xd9,
	0x09, 0x7b, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa6, 0xd3, 0xde, 0x5b, 0x22, 0x04, 0x00, 0x00,
}
