// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/admin/v2alpha/config_dump.proto

package envoy_admin_v2alpha

import (
	fmt "fmt"
	v21 "github.com/envoyproxy/go-control-plane/envoy/api/v2"
	auth "github.com/envoyproxy/go-control-plane/envoy/api/v2/auth"
	v2 "github.com/envoyproxy/go-control-plane/envoy/config/bootstrap/v2"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The :ref:`/config_dump <operations_admin_interface_config_dump>` admin endpoint uses this wrapper
// message to maintain and serve arbitrary configuration information from any component in Envoy.
type ConfigDump struct {
	// This list is serialized and dumped in its entirety at the
	// :ref:`/config_dump <operations_admin_interface_config_dump>` endpoint.
	//
	// The following configurations are currently supported and will be dumped in the order given
	// below:
	//
	// * *bootstrap*: :ref:`BootstrapConfigDump <envoy_api_msg_admin.v2alpha.BootstrapConfigDump>`
	// * *clusters*: :ref:`ClustersConfigDump <envoy_api_msg_admin.v2alpha.ClustersConfigDump>`
	// * *listeners*: :ref:`ListenersConfigDump <envoy_api_msg_admin.v2alpha.ListenersConfigDump>`
	// * *routes*:  :ref:`RoutesConfigDump <envoy_api_msg_admin.v2alpha.RoutesConfigDump>`
	Configs              []*any.Any `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ConfigDump) Reset()         { *m = ConfigDump{} }
func (m *ConfigDump) String() string { return proto.CompactTextString(m) }
func (*ConfigDump) ProtoMessage()    {}
func (*ConfigDump) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd4e190b1a64d2aa, []int{0}
}

func (m *ConfigDump) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigDump.Unmarshal(m, b)
}
func (m *ConfigDump) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigDump.Marshal(b, m, deterministic)
}
func (m *ConfigDump) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigDump.Merge(m, src)
}
func (m *ConfigDump) XXX_Size() int {
	return xxx_messageInfo_ConfigDump.Size(m)
}
func (m *ConfigDump) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigDump.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigDump proto.InternalMessageInfo

func (m *ConfigDump) GetConfigs() []*any.Any {
	if m != nil {
		return m.Configs
	}
	return nil
}

// This message describes the bootstrap configuration that Envoy was started with. This includes
// any CLI overrides that were merged. Bootstrap configuration information can be used to recreate
// the static portions of an Envoy configuration by reusing the output as the bootstrap
// configuration for another Envoy.
type BootstrapConfigDump struct {
	Bootstrap *v2.Bootstrap `protobuf:"bytes,1,opt,name=bootstrap,proto3" json:"bootstrap,omitempty"`
	// The timestamp when the BootstrapConfig was last updated.
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,2,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BootstrapConfigDump) Reset()         { *m = BootstrapConfigDump{} }
func (m *BootstrapConfigDump) String() string { return proto.CompactTextString(m) }
func (*BootstrapConfigDump) ProtoMessage()    {}
func (*BootstrapConfigDump) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd4e190b1a64d2aa, []int{1}
}

func (m *BootstrapConfigDump) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BootstrapConfigDump.Unmarshal(m, b)
}
func (m *BootstrapConfigDump) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BootstrapConfigDump.Marshal(b, m, deterministic)
}
func (m *BootstrapConfigDump) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BootstrapConfigDump.Merge(m, src)
}
func (m *BootstrapConfigDump) XXX_Size() int {
	return xxx_messageInfo_BootstrapConfigDump.Size(m)
}
func (m *BootstrapConfigDump) XXX_DiscardUnknown() {
	xxx_messageInfo_BootstrapConfigDump.DiscardUnknown(m)
}

var xxx_messageInfo_BootstrapConfigDump proto.InternalMessageInfo

func (m *BootstrapConfigDump) GetBootstrap() *v2.Bootstrap {
	if m != nil {
		return m.Bootstrap
	}
	return nil
}

func (m *BootstrapConfigDump) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

// Envoy's listener manager fills this message with all currently known listeners. Listener
// configuration information can be used to recreate an Envoy configuration by populating all
// listeners as static listeners or by returning them in a LDS response.
type ListenersConfigDump struct {
	// This is the :ref:`version_info <envoy_api_field_DiscoveryResponse.version_info>` in the
	// last processed LDS discovery response. If there are only static bootstrap listeners, this field
	// will be "".
	VersionInfo string `protobuf:"bytes,1,opt,name=version_info,json=versionInfo,proto3" json:"version_info,omitempty"`
	// The statically loaded listener configs.
	StaticListeners []*ListenersConfigDump_StaticListener `protobuf:"bytes,2,rep,name=static_listeners,json=staticListeners,proto3" json:"static_listeners,omitempty"`
	// The dynamically loaded active listeners. These are listeners that are available to service
	// data plane traffic.
	DynamicActiveListeners []*ListenersConfigDump_DynamicListener `protobuf:"bytes,3,rep,name=dynamic_active_listeners,json=dynamicActiveListeners,proto3" json:"dynamic_active_listeners,omitempty"`
	// The dynamically loaded warming listeners. These are listeners that are currently undergoing
	// warming in preparation to service data plane traffic. Note that if attempting to recreate an
	// Envoy configuration from a configuration dump, the warming listeners should generally be
	// discarded.
	DynamicWarmingListeners []*ListenersConfigDump_DynamicListener `protobuf:"bytes,4,rep,name=dynamic_warming_listeners,json=dynamicWarmingListeners,proto3" json:"dynamic_warming_listeners,omitempty"`
	// The dynamically loaded draining listeners. These are listeners that are currently undergoing
	// draining in preparation to stop servicing data plane traffic. Note that if attempting to
	// recreate an Envoy configuration from a configuration dump, the draining listeners should
	// generally be discarded.
	DynamicDrainingListeners []*ListenersConfigDump_DynamicListener `protobuf:"bytes,5,rep,name=dynamic_draining_listeners,json=dynamicDrainingListeners,proto3" json:"dynamic_draining_listeners,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                               `json:"-"`
	XXX_unrecognized         []byte                                 `json:"-"`
	XXX_sizecache            int32                                  `json:"-"`
}

func (m *ListenersConfigDump) Reset()         { *m = ListenersConfigDump{} }
func (m *ListenersConfigDump) String() string { return proto.CompactTextString(m) }
func (*ListenersConfigDump) ProtoMessage()    {}
func (*ListenersConfigDump) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd4e190b1a64d2aa, []int{2}
}

func (m *ListenersConfigDump) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenersConfigDump.Unmarshal(m, b)
}
func (m *ListenersConfigDump) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenersConfigDump.Marshal(b, m, deterministic)
}
func (m *ListenersConfigDump) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenersConfigDump.Merge(m, src)
}
func (m *ListenersConfigDump) XXX_Size() int {
	return xxx_messageInfo_ListenersConfigDump.Size(m)
}
func (m *ListenersConfigDump) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenersConfigDump.DiscardUnknown(m)
}

var xxx_messageInfo_ListenersConfigDump proto.InternalMessageInfo

func (m *ListenersConfigDump) GetVersionInfo() string {
	if m != nil {
		return m.VersionInfo
	}
	return ""
}

func (m *ListenersConfigDump) GetStaticListeners() []*ListenersConfigDump_StaticListener {
	if m != nil {
		return m.StaticListeners
	}
	return nil
}

func (m *ListenersConfigDump) GetDynamicActiveListeners() []*ListenersConfigDump_DynamicListener {
	if m != nil {
		return m.DynamicActiveListeners
	}
	return nil
}

func (m *ListenersConfigDump) GetDynamicWarmingListeners() []*ListenersConfigDump_DynamicListener {
	if m != nil {
		return m.DynamicWarmingListeners
	}
	return nil
}

func (m *ListenersConfigDump) GetDynamicDrainingListeners() []*ListenersConfigDump_DynamicListener {
	if m != nil {
		return m.DynamicDrainingListeners
	}
	return nil
}

// Describes a statically loaded listener.
type ListenersConfigDump_StaticListener struct {
	// The listener config.
	Listener *v21.Listener `protobuf:"bytes,1,opt,name=listener,proto3" json:"listener,omitempty"`
	// The timestamp when the Listener was last updated.
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,2,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListenersConfigDump_StaticListener) Reset()         { *m = ListenersConfigDump_StaticListener{} }
func (m *ListenersConfigDump_StaticListener) String() string { return proto.CompactTextString(m) }
func (*ListenersConfigDump_StaticListener) ProtoMessage()    {}
func (*ListenersConfigDump_StaticListener) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd4e190b1a64d2aa, []int{2, 0}
}

func (m *ListenersConfigDump_StaticListener) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenersConfigDump_StaticListener.Unmarshal(m, b)
}
func (m *ListenersConfigDump_StaticListener) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenersConfigDump_StaticListener.Marshal(b, m, deterministic)
}
func (m *ListenersConfigDump_StaticListener) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenersConfigDump_StaticListener.Merge(m, src)
}
func (m *ListenersConfigDump_StaticListener) XXX_Size() int {
	return xxx_messageInfo_ListenersConfigDump_StaticListener.Size(m)
}
func (m *ListenersConfigDump_StaticListener) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenersConfigDump_StaticListener.DiscardUnknown(m)
}

var xxx_messageInfo_ListenersConfigDump_StaticListener proto.InternalMessageInfo

func (m *ListenersConfigDump_StaticListener) GetListener() *v21.Listener {
	if m != nil {
		return m.Listener
	}
	return nil
}

func (m *ListenersConfigDump_StaticListener) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

// Describes a dynamically loaded cluster via the LDS API.
type ListenersConfigDump_DynamicListener struct {
	// This is the per-resource version information. This version is currently taken from the
	// :ref:`version_info <envoy_api_field_DiscoveryResponse.version_info>` field at the time
	// that the listener was loaded. In the future, discrete per-listener versions may be supported
	// by the API.
	VersionInfo string `protobuf:"bytes,1,opt,name=version_info,json=versionInfo,proto3" json:"version_info,omitempty"`
	// The listener config.
	Listener *v21.Listener `protobuf:"bytes,2,opt,name=listener,proto3" json:"listener,omitempty"`
	// The timestamp when the Listener was last updated.
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListenersConfigDump_DynamicListener) Reset()         { *m = ListenersConfigDump_DynamicListener{} }
func (m *ListenersConfigDump_DynamicListener) String() string { return proto.CompactTextString(m) }
func (*ListenersConfigDump_DynamicListener) ProtoMessage()    {}
func (*ListenersConfigDump_DynamicListener) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd4e190b1a64d2aa, []int{2, 1}
}

func (m *ListenersConfigDump_DynamicListener) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenersConfigDump_DynamicListener.Unmarshal(m, b)
}
func (m *ListenersConfigDump_DynamicListener) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenersConfigDump_DynamicListener.Marshal(b, m, deterministic)
}
func (m *ListenersConfigDump_DynamicListener) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenersConfigDump_DynamicListener.Merge(m, src)
}
func (m *ListenersConfigDump_DynamicListener) XXX_Size() int {
	return xxx_messageInfo_ListenersConfigDump_DynamicListener.Size(m)
}
func (m *ListenersConfigDump_DynamicListener) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenersConfigDump_DynamicListener.DiscardUnknown(m)
}

var xxx_messageInfo_ListenersConfigDump_DynamicListener proto.InternalMessageInfo

func (m *ListenersConfigDump_DynamicListener) GetVersionInfo() string {
	if m != nil {
		return m.VersionInfo
	}
	return ""
}

func (m *ListenersConfigDump_DynamicListener) GetListener() *v21.Listener {
	if m != nil {
		return m.Listener
	}
	return nil
}

func (m *ListenersConfigDump_DynamicListener) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

// Envoy's cluster manager fills this message with all currently known clusters. Cluster
// configuration information can be used to recreate an Envoy configuration by populating all
// clusters as static clusters or by returning them in a CDS response.
type ClustersConfigDump struct {
	// This is the :ref:`version_info <envoy_api_field_DiscoveryResponse.version_info>` in the
	// last processed CDS discovery response. If there are only static bootstrap clusters, this field
	// will be "".
	VersionInfo string `protobuf:"bytes,1,opt,name=version_info,json=versionInfo,proto3" json:"version_info,omitempty"`
	// The statically loaded cluster configs.
	StaticClusters []*ClustersConfigDump_StaticCluster `protobuf:"bytes,2,rep,name=static_clusters,json=staticClusters,proto3" json:"static_clusters,omitempty"`
	// The dynamically loaded active clusters. These are clusters that are available to service
	// data plane traffic.
	DynamicActiveClusters []*ClustersConfigDump_DynamicCluster `protobuf:"bytes,3,rep,name=dynamic_active_clusters,json=dynamicActiveClusters,proto3" json:"dynamic_active_clusters,omitempty"`
	// The dynamically loaded warming clusters. These are clusters that are currently undergoing
	// warming in preparation to service data plane traffic. Note that if attempting to recreate an
	// Envoy configuration from a configuration dump, the warming clusters should generally be
	// discarded.
	DynamicWarmingClusters []*ClustersConfigDump_DynamicCluster `protobuf:"bytes,4,rep,name=dynamic_warming_clusters,json=dynamicWarmingClusters,proto3" json:"dynamic_warming_clusters,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                             `json:"-"`
	XXX_unrecognized       []byte                               `json:"-"`
	XXX_sizecache          int32                                `json:"-"`
}

func (m *ClustersConfigDump) Reset()         { *m = ClustersConfigDump{} }
func (m *ClustersConfigDump) String() string { return proto.CompactTextString(m) }
func (*ClustersConfigDump) ProtoMessage()    {}
func (*ClustersConfigDump) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd4e190b1a64d2aa, []int{3}
}

func (m *ClustersConfigDump) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClustersConfigDump.Unmarshal(m, b)
}
func (m *ClustersConfigDump) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClustersConfigDump.Marshal(b, m, deterministic)
}
func (m *ClustersConfigDump) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClustersConfigDump.Merge(m, src)
}
func (m *ClustersConfigDump) XXX_Size() int {
	return xxx_messageInfo_ClustersConfigDump.Size(m)
}
func (m *ClustersConfigDump) XXX_DiscardUnknown() {
	xxx_messageInfo_ClustersConfigDump.DiscardUnknown(m)
}

var xxx_messageInfo_ClustersConfigDump proto.InternalMessageInfo

func (m *ClustersConfigDump) GetVersionInfo() string {
	if m != nil {
		return m.VersionInfo
	}
	return ""
}

func (m *ClustersConfigDump) GetStaticClusters() []*ClustersConfigDump_StaticCluster {
	if m != nil {
		return m.StaticClusters
	}
	return nil
}

func (m *ClustersConfigDump) GetDynamicActiveClusters() []*ClustersConfigDump_DynamicCluster {
	if m != nil {
		return m.DynamicActiveClusters
	}
	return nil
}

func (m *ClustersConfigDump) GetDynamicWarmingClusters() []*ClustersConfigDump_DynamicCluster {
	if m != nil {
		return m.DynamicWarmingClusters
	}
	return nil
}

// Describes a statically loaded cluster.
type ClustersConfigDump_StaticCluster struct {
	// The cluster config.
	Cluster *v21.Cluster `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// The timestamp when the Cluster was last updated.
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,2,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ClustersConfigDump_StaticCluster) Reset()         { *m = ClustersConfigDump_StaticCluster{} }
func (m *ClustersConfigDump_StaticCluster) String() string { return proto.CompactTextString(m) }
func (*ClustersConfigDump_StaticCluster) ProtoMessage()    {}
func (*ClustersConfigDump_StaticCluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd4e190b1a64d2aa, []int{3, 0}
}

func (m *ClustersConfigDump_StaticCluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClustersConfigDump_StaticCluster.Unmarshal(m, b)
}
func (m *ClustersConfigDump_StaticCluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClustersConfigDump_StaticCluster.Marshal(b, m, deterministic)
}
func (m *ClustersConfigDump_StaticCluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClustersConfigDump_StaticCluster.Merge(m, src)
}
func (m *ClustersConfigDump_StaticCluster) XXX_Size() int {
	return xxx_messageInfo_ClustersConfigDump_StaticCluster.Size(m)
}
func (m *ClustersConfigDump_StaticCluster) XXX_DiscardUnknown() {
	xxx_messageInfo_ClustersConfigDump_StaticCluster.DiscardUnknown(m)
}

var xxx_messageInfo_ClustersConfigDump_StaticCluster proto.InternalMessageInfo

func (m *ClustersConfigDump_StaticCluster) GetCluster() *v21.Cluster {
	if m != nil {
		return m.Cluster
	}
	return nil
}

func (m *ClustersConfigDump_StaticCluster) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

// Describes a dynamically loaded cluster via the CDS API.
type ClustersConfigDump_DynamicCluster struct {
	// This is the per-resource version information. This version is currently taken from the
	// :ref:`version_info <envoy_api_field_DiscoveryResponse.version_info>` field at the time
	// that the cluster was loaded. In the future, discrete per-cluster versions may be supported by
	// the API.
	VersionInfo string `protobuf:"bytes,1,opt,name=version_info,json=versionInfo,proto3" json:"version_info,omitempty"`
	// The cluster config.
	Cluster *v21.Cluster `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// The timestamp when the Cluster was last updated.
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ClustersConfigDump_DynamicCluster) Reset()         { *m = ClustersConfigDump_DynamicCluster{} }
func (m *ClustersConfigDump_DynamicCluster) String() string { return proto.CompactTextString(m) }
func (*ClustersConfigDump_DynamicCluster) ProtoMessage()    {}
func (*ClustersConfigDump_DynamicCluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd4e190b1a64d2aa, []int{3, 1}
}

func (m *ClustersConfigDump_DynamicCluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClustersConfigDump_DynamicCluster.Unmarshal(m, b)
}
func (m *ClustersConfigDump_DynamicCluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClustersConfigDump_DynamicCluster.Marshal(b, m, deterministic)
}
func (m *ClustersConfigDump_DynamicCluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClustersConfigDump_DynamicCluster.Merge(m, src)
}
func (m *ClustersConfigDump_DynamicCluster) XXX_Size() int {
	return xxx_messageInfo_ClustersConfigDump_DynamicCluster.Size(m)
}
func (m *ClustersConfigDump_DynamicCluster) XXX_DiscardUnknown() {
	xxx_messageInfo_ClustersConfigDump_DynamicCluster.DiscardUnknown(m)
}

var xxx_messageInfo_ClustersConfigDump_DynamicCluster proto.InternalMessageInfo

func (m *ClustersConfigDump_DynamicCluster) GetVersionInfo() string {
	if m != nil {
		return m.VersionInfo
	}
	return ""
}

func (m *ClustersConfigDump_DynamicCluster) GetCluster() *v21.Cluster {
	if m != nil {
		return m.Cluster
	}
	return nil
}

func (m *ClustersConfigDump_DynamicCluster) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

// Envoy's RDS implementation fills this message with all currently loaded routes, as described by
// their RouteConfiguration objects. Static routes configured in the bootstrap configuration are
// separated from those configured dynamically via RDS. Route configuration information can be used
// to recreate an Envoy configuration by populating all routes as static routes or by returning them
// in RDS responses.
type RoutesConfigDump struct {
	// The statically loaded route configs.
	StaticRouteConfigs []*RoutesConfigDump_StaticRouteConfig `protobuf:"bytes,2,rep,name=static_route_configs,json=staticRouteConfigs,proto3" json:"static_route_configs,omitempty"`
	// The dynamically loaded route configs.
	DynamicRouteConfigs  []*RoutesConfigDump_DynamicRouteConfig `protobuf:"bytes,3,rep,name=dynamic_route_configs,json=dynamicRouteConfigs,proto3" json:"dynamic_route_configs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *RoutesConfigDump) Reset()         { *m = RoutesConfigDump{} }
func (m *RoutesConfigDump) String() string { return proto.CompactTextString(m) }
func (*RoutesConfigDump) ProtoMessage()    {}
func (*RoutesConfigDump) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd4e190b1a64d2aa, []int{4}
}

func (m *RoutesConfigDump) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoutesConfigDump.Unmarshal(m, b)
}
func (m *RoutesConfigDump) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoutesConfigDump.Marshal(b, m, deterministic)
}
func (m *RoutesConfigDump) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoutesConfigDump.Merge(m, src)
}
func (m *RoutesConfigDump) XXX_Size() int {
	return xxx_messageInfo_RoutesConfigDump.Size(m)
}
func (m *RoutesConfigDump) XXX_DiscardUnknown() {
	xxx_messageInfo_RoutesConfigDump.DiscardUnknown(m)
}

var xxx_messageInfo_RoutesConfigDump proto.InternalMessageInfo

func (m *RoutesConfigDump) GetStaticRouteConfigs() []*RoutesConfigDump_StaticRouteConfig {
	if m != nil {
		return m.StaticRouteConfigs
	}
	return nil
}

func (m *RoutesConfigDump) GetDynamicRouteConfigs() []*RoutesConfigDump_DynamicRouteConfig {
	if m != nil {
		return m.DynamicRouteConfigs
	}
	return nil
}

type RoutesConfigDump_StaticRouteConfig struct {
	// The route config.
	RouteConfig *v21.RouteConfiguration `protobuf:"bytes,1,opt,name=route_config,json=routeConfig,proto3" json:"route_config,omitempty"`
	// The timestamp when the Route was last updated.
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,2,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RoutesConfigDump_StaticRouteConfig) Reset()         { *m = RoutesConfigDump_StaticRouteConfig{} }
func (m *RoutesConfigDump_StaticRouteConfig) String() string { return proto.CompactTextString(m) }
func (*RoutesConfigDump_StaticRouteConfig) ProtoMessage()    {}
func (*RoutesConfigDump_StaticRouteConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd4e190b1a64d2aa, []int{4, 0}
}

func (m *RoutesConfigDump_StaticRouteConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoutesConfigDump_StaticRouteConfig.Unmarshal(m, b)
}
func (m *RoutesConfigDump_StaticRouteConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoutesConfigDump_StaticRouteConfig.Marshal(b, m, deterministic)
}
func (m *RoutesConfigDump_StaticRouteConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoutesConfigDump_StaticRouteConfig.Merge(m, src)
}
func (m *RoutesConfigDump_StaticRouteConfig) XXX_Size() int {
	return xxx_messageInfo_RoutesConfigDump_StaticRouteConfig.Size(m)
}
func (m *RoutesConfigDump_StaticRouteConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RoutesConfigDump_StaticRouteConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RoutesConfigDump_StaticRouteConfig proto.InternalMessageInfo

func (m *RoutesConfigDump_StaticRouteConfig) GetRouteConfig() *v21.RouteConfiguration {
	if m != nil {
		return m.RouteConfig
	}
	return nil
}

func (m *RoutesConfigDump_StaticRouteConfig) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type RoutesConfigDump_DynamicRouteConfig struct {
	// This is the per-resource version information. This version is currently taken from the
	// :ref:`version_info <envoy_api_field_DiscoveryResponse.version_info>` field at the time that
	// the route configuration was loaded.
	VersionInfo string `protobuf:"bytes,1,opt,name=version_info,json=versionInfo,proto3" json:"version_info,omitempty"`
	// The route config.
	RouteConfig *v21.RouteConfiguration `protobuf:"bytes,2,opt,name=route_config,json=routeConfig,proto3" json:"route_config,omitempty"`
	// The timestamp when the Route was last updated.
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RoutesConfigDump_DynamicRouteConfig) Reset()         { *m = RoutesConfigDump_DynamicRouteConfig{} }
func (m *RoutesConfigDump_DynamicRouteConfig) String() string { return proto.CompactTextString(m) }
func (*RoutesConfigDump_DynamicRouteConfig) ProtoMessage()    {}
func (*RoutesConfigDump_DynamicRouteConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd4e190b1a64d2aa, []int{4, 1}
}

func (m *RoutesConfigDump_DynamicRouteConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoutesConfigDump_DynamicRouteConfig.Unmarshal(m, b)
}
func (m *RoutesConfigDump_DynamicRouteConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoutesConfigDump_DynamicRouteConfig.Marshal(b, m, deterministic)
}
func (m *RoutesConfigDump_DynamicRouteConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoutesConfigDump_DynamicRouteConfig.Merge(m, src)
}
func (m *RoutesConfigDump_DynamicRouteConfig) XXX_Size() int {
	return xxx_messageInfo_RoutesConfigDump_DynamicRouteConfig.Size(m)
}
func (m *RoutesConfigDump_DynamicRouteConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RoutesConfigDump_DynamicRouteConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RoutesConfigDump_DynamicRouteConfig proto.InternalMessageInfo

func (m *RoutesConfigDump_DynamicRouteConfig) GetVersionInfo() string {
	if m != nil {
		return m.VersionInfo
	}
	return ""
}

func (m *RoutesConfigDump_DynamicRouteConfig) GetRouteConfig() *v21.RouteConfiguration {
	if m != nil {
		return m.RouteConfig
	}
	return nil
}

func (m *RoutesConfigDump_DynamicRouteConfig) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

// Envoy's scoped RDS implementation fills this message with all currently loaded route
// configuration scopes (defined via ScopedRouteConfigurationsSet protos). This message lists both
// the scopes defined inline with the higher order object (i.e., the HttpConnectionManager) and the
// dynamically obtained scopes via the SRDS API.
type ScopedRoutesConfigDump struct {
	// The statically loaded scoped route configs.
	InlineScopedRouteConfigs []*ScopedRoutesConfigDump_InlineScopedRouteConfigs `protobuf:"bytes,1,rep,name=inline_scoped_route_configs,json=inlineScopedRouteConfigs,proto3" json:"inline_scoped_route_configs,omitempty"`
	// The dynamically loaded scoped route configs.
	DynamicScopedRouteConfigs []*ScopedRoutesConfigDump_DynamicScopedRouteConfigs `protobuf:"bytes,2,rep,name=dynamic_scoped_route_configs,json=dynamicScopedRouteConfigs,proto3" json:"dynamic_scoped_route_configs,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                                            `json:"-"`
	XXX_unrecognized          []byte                                              `json:"-"`
	XXX_sizecache             int32                                               `json:"-"`
}

func (m *ScopedRoutesConfigDump) Reset()         { *m = ScopedRoutesConfigDump{} }
func (m *ScopedRoutesConfigDump) String() string { return proto.CompactTextString(m) }
func (*ScopedRoutesConfigDump) ProtoMessage()    {}
func (*ScopedRoutesConfigDump) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd4e190b1a64d2aa, []int{5}
}

func (m *ScopedRoutesConfigDump) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScopedRoutesConfigDump.Unmarshal(m, b)
}
func (m *ScopedRoutesConfigDump) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScopedRoutesConfigDump.Marshal(b, m, deterministic)
}
func (m *ScopedRoutesConfigDump) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScopedRoutesConfigDump.Merge(m, src)
}
func (m *ScopedRoutesConfigDump) XXX_Size() int {
	return xxx_messageInfo_ScopedRoutesConfigDump.Size(m)
}
func (m *ScopedRoutesConfigDump) XXX_DiscardUnknown() {
	xxx_messageInfo_ScopedRoutesConfigDump.DiscardUnknown(m)
}

var xxx_messageInfo_ScopedRoutesConfigDump proto.InternalMessageInfo

func (m *ScopedRoutesConfigDump) GetInlineScopedRouteConfigs() []*ScopedRoutesConfigDump_InlineScopedRouteConfigs {
	if m != nil {
		return m.InlineScopedRouteConfigs
	}
	return nil
}

func (m *ScopedRoutesConfigDump) GetDynamicScopedRouteConfigs() []*ScopedRoutesConfigDump_DynamicScopedRouteConfigs {
	if m != nil {
		return m.DynamicScopedRouteConfigs
	}
	return nil
}

type ScopedRoutesConfigDump_InlineScopedRouteConfigs struct {
	// The name assigned to the scoped route configurations.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The scoped route configurations.
	ScopedRouteConfigs []*v21.ScopedRouteConfiguration `protobuf:"bytes,2,rep,name=scoped_route_configs,json=scopedRouteConfigs,proto3" json:"scoped_route_configs,omitempty"`
	// The timestamp when the scoped route config set was last updated.
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ScopedRoutesConfigDump_InlineScopedRouteConfigs) Reset() {
	*m = ScopedRoutesConfigDump_InlineScopedRouteConfigs{}
}
func (m *ScopedRoutesConfigDump_InlineScopedRouteConfigs) String() string {
	return proto.CompactTextString(m)
}
func (*ScopedRoutesConfigDump_InlineScopedRouteConfigs) ProtoMessage() {}
func (*ScopedRoutesConfigDump_InlineScopedRouteConfigs) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd4e190b1a64d2aa, []int{5, 0}
}

func (m *ScopedRoutesConfigDump_InlineScopedRouteConfigs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScopedRoutesConfigDump_InlineScopedRouteConfigs.Unmarshal(m, b)
}
func (m *ScopedRoutesConfigDump_InlineScopedRouteConfigs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScopedRoutesConfigDump_InlineScopedRouteConfigs.Marshal(b, m, deterministic)
}
func (m *ScopedRoutesConfigDump_InlineScopedRouteConfigs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScopedRoutesConfigDump_InlineScopedRouteConfigs.Merge(m, src)
}
func (m *ScopedRoutesConfigDump_InlineScopedRouteConfigs) XXX_Size() int {
	return xxx_messageInfo_ScopedRoutesConfigDump_InlineScopedRouteConfigs.Size(m)
}
func (m *ScopedRoutesConfigDump_InlineScopedRouteConfigs) XXX_DiscardUnknown() {
	xxx_messageInfo_ScopedRoutesConfigDump_InlineScopedRouteConfigs.DiscardUnknown(m)
}

var xxx_messageInfo_ScopedRoutesConfigDump_InlineScopedRouteConfigs proto.InternalMessageInfo

func (m *ScopedRoutesConfigDump_InlineScopedRouteConfigs) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ScopedRoutesConfigDump_InlineScopedRouteConfigs) GetScopedRouteConfigs() []*v21.ScopedRouteConfiguration {
	if m != nil {
		return m.ScopedRouteConfigs
	}
	return nil
}

func (m *ScopedRoutesConfigDump_InlineScopedRouteConfigs) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type ScopedRoutesConfigDump_DynamicScopedRouteConfigs struct {
	// The name assigned to the scoped route configurations.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// This is the per-resource version information. This version is currently taken from the
	// :ref:`version_info <envoy_api_field_DiscoveryResponse.version_info>` field at the time that
	// the scoped routes configuration was loaded.
	VersionInfo string `protobuf:"bytes,2,opt,name=version_info,json=versionInfo,proto3" json:"version_info,omitempty"`
	// The scoped route configurations.
	ScopedRouteConfigs []*v21.ScopedRouteConfiguration `protobuf:"bytes,3,rep,name=scoped_route_configs,json=scopedRouteConfigs,proto3" json:"scoped_route_configs,omitempty"`
	// The timestamp when the scoped route config set was last updated.
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ScopedRoutesConfigDump_DynamicScopedRouteConfigs) Reset() {
	*m = ScopedRoutesConfigDump_DynamicScopedRouteConfigs{}
}
func (m *ScopedRoutesConfigDump_DynamicScopedRouteConfigs) String() string {
	return proto.CompactTextString(m)
}
func (*ScopedRoutesConfigDump_DynamicScopedRouteConfigs) ProtoMessage() {}
func (*ScopedRoutesConfigDump_DynamicScopedRouteConfigs) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd4e190b1a64d2aa, []int{5, 1}
}

func (m *ScopedRoutesConfigDump_DynamicScopedRouteConfigs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScopedRoutesConfigDump_DynamicScopedRouteConfigs.Unmarshal(m, b)
}
func (m *ScopedRoutesConfigDump_DynamicScopedRouteConfigs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScopedRoutesConfigDump_DynamicScopedRouteConfigs.Marshal(b, m, deterministic)
}
func (m *ScopedRoutesConfigDump_DynamicScopedRouteConfigs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScopedRoutesConfigDump_DynamicScopedRouteConfigs.Merge(m, src)
}
func (m *ScopedRoutesConfigDump_DynamicScopedRouteConfigs) XXX_Size() int {
	return xxx_messageInfo_ScopedRoutesConfigDump_DynamicScopedRouteConfigs.Size(m)
}
func (m *ScopedRoutesConfigDump_DynamicScopedRouteConfigs) XXX_DiscardUnknown() {
	xxx_messageInfo_ScopedRoutesConfigDump_DynamicScopedRouteConfigs.DiscardUnknown(m)
}

var xxx_messageInfo_ScopedRoutesConfigDump_DynamicScopedRouteConfigs proto.InternalMessageInfo

func (m *ScopedRoutesConfigDump_DynamicScopedRouteConfigs) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ScopedRoutesConfigDump_DynamicScopedRouteConfigs) GetVersionInfo() string {
	if m != nil {
		return m.VersionInfo
	}
	return ""
}

func (m *ScopedRoutesConfigDump_DynamicScopedRouteConfigs) GetScopedRouteConfigs() []*v21.ScopedRouteConfiguration {
	if m != nil {
		return m.ScopedRouteConfigs
	}
	return nil
}

func (m *ScopedRoutesConfigDump_DynamicScopedRouteConfigs) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

// Envoys SDS implementation fills this message with all secrets fetched dynamically via SDS.
type SecretsConfigDump struct {
	// The statically loaded secrets.
	StaticSecrets []*SecretsConfigDump_StaticSecret `protobuf:"bytes,1,rep,name=static_secrets,json=staticSecrets,proto3" json:"static_secrets,omitempty"`
	// The dynamically loaded active secrets. These are secrets that are available to service
	// clusters or listeners.
	DynamicActiveSecrets []*SecretsConfigDump_DynamicSecret `protobuf:"bytes,2,rep,name=dynamic_active_secrets,json=dynamicActiveSecrets,proto3" json:"dynamic_active_secrets,omitempty"`
	// The dynamically loaded warming secrets. These are secrets that are currently undergoing
	// warming in preparation to service clusters or listeners.
	DynamicWarmingSecrets []*SecretsConfigDump_DynamicSecret `protobuf:"bytes,3,rep,name=dynamic_warming_secrets,json=dynamicWarmingSecrets,proto3" json:"dynamic_warming_secrets,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                           `json:"-"`
	XXX_unrecognized      []byte                             `json:"-"`
	XXX_sizecache         int32                              `json:"-"`
}

func (m *SecretsConfigDump) Reset()         { *m = SecretsConfigDump{} }
func (m *SecretsConfigDump) String() string { return proto.CompactTextString(m) }
func (*SecretsConfigDump) ProtoMessage()    {}
func (*SecretsConfigDump) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd4e190b1a64d2aa, []int{6}
}

func (m *SecretsConfigDump) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretsConfigDump.Unmarshal(m, b)
}
func (m *SecretsConfigDump) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretsConfigDump.Marshal(b, m, deterministic)
}
func (m *SecretsConfigDump) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretsConfigDump.Merge(m, src)
}
func (m *SecretsConfigDump) XXX_Size() int {
	return xxx_messageInfo_SecretsConfigDump.Size(m)
}
func (m *SecretsConfigDump) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretsConfigDump.DiscardUnknown(m)
}

var xxx_messageInfo_SecretsConfigDump proto.InternalMessageInfo

func (m *SecretsConfigDump) GetStaticSecrets() []*SecretsConfigDump_StaticSecret {
	if m != nil {
		return m.StaticSecrets
	}
	return nil
}

func (m *SecretsConfigDump) GetDynamicActiveSecrets() []*SecretsConfigDump_DynamicSecret {
	if m != nil {
		return m.DynamicActiveSecrets
	}
	return nil
}

func (m *SecretsConfigDump) GetDynamicWarmingSecrets() []*SecretsConfigDump_DynamicSecret {
	if m != nil {
		return m.DynamicWarmingSecrets
	}
	return nil
}

// DynamicSecret contains secret information fetched via SDS.
type SecretsConfigDump_DynamicSecret struct {
	// The name assigned to the secret.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// This is the per-resource version information.
	VersionInfo string `protobuf:"bytes,2,opt,name=version_info,json=versionInfo,proto3" json:"version_info,omitempty"`
	// The timestamp when the secret was last updated.
	LastUpdated *timestamp.Timestamp `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	// The actual secret information.
	// Security sensitive information is redacted (replaced with "[redacted]") for
	// private keys and passwords in TLS certificates.
	Secret               *auth.Secret `protobuf:"bytes,4,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SecretsConfigDump_DynamicSecret) Reset()         { *m = SecretsConfigDump_DynamicSecret{} }
func (m *SecretsConfigDump_DynamicSecret) String() string { return proto.CompactTextString(m) }
func (*SecretsConfigDump_DynamicSecret) ProtoMessage()    {}
func (*SecretsConfigDump_DynamicSecret) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd4e190b1a64d2aa, []int{6, 0}
}

func (m *SecretsConfigDump_DynamicSecret) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretsConfigDump_DynamicSecret.Unmarshal(m, b)
}
func (m *SecretsConfigDump_DynamicSecret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretsConfigDump_DynamicSecret.Marshal(b, m, deterministic)
}
func (m *SecretsConfigDump_DynamicSecret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretsConfigDump_DynamicSecret.Merge(m, src)
}
func (m *SecretsConfigDump_DynamicSecret) XXX_Size() int {
	return xxx_messageInfo_SecretsConfigDump_DynamicSecret.Size(m)
}
func (m *SecretsConfigDump_DynamicSecret) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretsConfigDump_DynamicSecret.DiscardUnknown(m)
}

var xxx_messageInfo_SecretsConfigDump_DynamicSecret proto.InternalMessageInfo

func (m *SecretsConfigDump_DynamicSecret) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SecretsConfigDump_DynamicSecret) GetVersionInfo() string {
	if m != nil {
		return m.VersionInfo
	}
	return ""
}

func (m *SecretsConfigDump_DynamicSecret) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

func (m *SecretsConfigDump_DynamicSecret) GetSecret() *auth.Secret {
	if m != nil {
		return m.Secret
	}
	return nil
}

// StaticSecret specifies statically loaded secret in bootstrap.
type SecretsConfigDump_StaticSecret struct {
	// The name assigned to the secret.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The timestamp when the secret was last updated.
	LastUpdated *timestamp.Timestamp `protobuf:"bytes,2,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	// The actual secret information.
	// Security sensitive information is redacted (replaced with "[redacted]") for
	// private keys and passwords in TLS certificates.
	Secret               *auth.Secret `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SecretsConfigDump_StaticSecret) Reset()         { *m = SecretsConfigDump_StaticSecret{} }
func (m *SecretsConfigDump_StaticSecret) String() string { return proto.CompactTextString(m) }
func (*SecretsConfigDump_StaticSecret) ProtoMessage()    {}
func (*SecretsConfigDump_StaticSecret) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd4e190b1a64d2aa, []int{6, 1}
}

func (m *SecretsConfigDump_StaticSecret) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretsConfigDump_StaticSecret.Unmarshal(m, b)
}
func (m *SecretsConfigDump_StaticSecret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretsConfigDump_StaticSecret.Marshal(b, m, deterministic)
}
func (m *SecretsConfigDump_StaticSecret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretsConfigDump_StaticSecret.Merge(m, src)
}
func (m *SecretsConfigDump_StaticSecret) XXX_Size() int {
	return xxx_messageInfo_SecretsConfigDump_StaticSecret.Size(m)
}
func (m *SecretsConfigDump_StaticSecret) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretsConfigDump_StaticSecret.DiscardUnknown(m)
}

var xxx_messageInfo_SecretsConfigDump_StaticSecret proto.InternalMessageInfo

func (m *SecretsConfigDump_StaticSecret) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SecretsConfigDump_StaticSecret) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

func (m *SecretsConfigDump_StaticSecret) GetSecret() *auth.Secret {
	if m != nil {
		return m.Secret
	}
	return nil
}

func init() {
	proto.RegisterType((*ConfigDump)(nil), "envoy.admin.v2alpha.ConfigDump")
	proto.RegisterType((*BootstrapConfigDump)(nil), "envoy.admin.v2alpha.BootstrapConfigDump")
	proto.RegisterType((*ListenersConfigDump)(nil), "envoy.admin.v2alpha.ListenersConfigDump")
	proto.RegisterType((*ListenersConfigDump_StaticListener)(nil), "envoy.admin.v2alpha.ListenersConfigDump.StaticListener")
	proto.RegisterType((*ListenersConfigDump_DynamicListener)(nil), "envoy.admin.v2alpha.ListenersConfigDump.DynamicListener")
	proto.RegisterType((*ClustersConfigDump)(nil), "envoy.admin.v2alpha.ClustersConfigDump")
	proto.RegisterType((*ClustersConfigDump_StaticCluster)(nil), "envoy.admin.v2alpha.ClustersConfigDump.StaticCluster")
	proto.RegisterType((*ClustersConfigDump_DynamicCluster)(nil), "envoy.admin.v2alpha.ClustersConfigDump.DynamicCluster")
	proto.RegisterType((*RoutesConfigDump)(nil), "envoy.admin.v2alpha.RoutesConfigDump")
	proto.RegisterType((*RoutesConfigDump_StaticRouteConfig)(nil), "envoy.admin.v2alpha.RoutesConfigDump.StaticRouteConfig")
	proto.RegisterType((*RoutesConfigDump_DynamicRouteConfig)(nil), "envoy.admin.v2alpha.RoutesConfigDump.DynamicRouteConfig")
	proto.RegisterType((*ScopedRoutesConfigDump)(nil), "envoy.admin.v2alpha.ScopedRoutesConfigDump")
	proto.RegisterType((*ScopedRoutesConfigDump_InlineScopedRouteConfigs)(nil), "envoy.admin.v2alpha.ScopedRoutesConfigDump.InlineScopedRouteConfigs")
	proto.RegisterType((*ScopedRoutesConfigDump_DynamicScopedRouteConfigs)(nil), "envoy.admin.v2alpha.ScopedRoutesConfigDump.DynamicScopedRouteConfigs")
	proto.RegisterType((*SecretsConfigDump)(nil), "envoy.admin.v2alpha.SecretsConfigDump")
	proto.RegisterType((*SecretsConfigDump_DynamicSecret)(nil), "envoy.admin.v2alpha.SecretsConfigDump.DynamicSecret")
	proto.RegisterType((*SecretsConfigDump_StaticSecret)(nil), "envoy.admin.v2alpha.SecretsConfigDump.StaticSecret")
}

func init() {
	proto.RegisterFile("envoy/admin/v2alpha/config_dump.proto", fileDescriptor_bd4e190b1a64d2aa)
}

var fileDescriptor_bd4e190b1a64d2aa = []byte{
	// 992 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0x97, 0x93, 0xb4, 0xcb, 0xbe, 0xf4, 0xcf, 0xee, 0x34, 0x4d, 0x53, 0xb3, 0x12, 0xdd, 0x0a,
	0xd0, 0x72, 0xb1, 0x45, 0x16, 0x16, 0x0e, 0x70, 0xd8, 0xb6, 0x1c, 0x56, 0xe2, 0xb0, 0x72, 0x41,
	0x20, 0x0e, 0x58, 0xae, 0xed, 0x66, 0x07, 0x39, 0x33, 0x96, 0x67, 0x12, 0xc8, 0x89, 0xc3, 0x4a,
	0x7c, 0x02, 0x24, 0x90, 0xb8, 0x20, 0x71, 0xe0, 0xc6, 0x19, 0x89, 0x23, 0x07, 0x3e, 0x06, 0x1f,
	0x80, 0x2f, 0x81, 0xe2, 0x99, 0xb1, 0x67, 0x6c, 0xa7, 0x4a, 0xea, 0xbd, 0xc5, 0xef, 0xbd, 0xf9,
	0xfd, 0x7e, 0x33, 0xef, 0xf7, 0x3c, 0x0e, 0xbc, 0x15, 0x93, 0x39, 0x5d, 0xb8, 0x41, 0x34, 0xc5,
	0xc4, 0x9d, 0x8f, 0x83, 0x24, 0x7d, 0x11, 0xb8, 0x21, 0x25, 0xd7, 0x78, 0xe2, 0x47, 0xb3, 0x69,
	0xea, 0xa4, 0x19, 0xe5, 0x14, 0x1d, 0xe4, 0x65, 0x4e, 0x5e, 0xe6, 0xc8, 0x32, 0xfb, 0x81, 0x5c,
	0x9b, 0x62, 0x77, 0x3e, 0x76, 0x83, 0x19, 0x7f, 0xe1, 0x86, 0x71, 0xc6, 0xc5, 0x12, 0x7b, 0x68,
	0x64, 0xc3, 0x88, 0x35, 0xc6, 0x93, 0x15, 0xf1, 0xac, 0x88, 0x1f, 0x19, 0x71, 0x56, 0x26, 0xde,
	0x11, 0x09, 0x21, 0xd6, 0xbd, 0xa2, 0x94, 0x33, 0x9e, 0x05, 0xe9, 0xb2, 0xaa, 0x78, 0x90, 0xa5,
	0xc7, 0x13, 0x4a, 0x27, 0x49, 0xec, 0xe6, 0x4f, 0x57, 0xb3, 0x6b, 0x37, 0x20, 0x0b, 0x99, 0x7a,
	0xa3, 0x9a, 0xe2, 0x78, 0x1a, 0x33, 0x1e, 0xa8, 0xad, 0xdb, 0x83, 0x09, 0x9d, 0xd0, 0xfc, 0xa7,
	0xbb, 0xfc, 0x25, 0xa2, 0xa7, 0x1f, 0x01, 0x9c, 0xe7, 0xc4, 0x17, 0xb3, 0x69, 0x8a, 0x1c, 0xb8,
	0x23, 0x64, 0xb0, 0x91, 0x75, 0xd2, 0x7d, 0xd4, 0x1f, 0x0f, 0x1c, 0x01, 0xeb, 0x28, 0x58, 0xe7,
	0x29, 0x59, 0x78, 0xaa, 0xe8, 0xf4, 0x67, 0x0b, 0x0e, 0xce, 0x94, 0x46, 0x0d, 0xe7, 0x0c, 0xee,
	0x16, 0xd2, 0x47, 0xd6, 0x89, 0xf5, 0xa8, 0x3f, 0x7e, 0xd3, 0x11, 0x47, 0x2f, 0x96, 0x3a, 0xe5,
	0xce, 0xe6, 0x63, 0xa7, 0x80, 0xf0, 0xca, 0x65, 0xe8, 0x63, 0xd8, 0x49, 0x02, 0xc6, 0xfd, 0x59,
	0x1a, 0x05, 0x3c, 0x8e, 0x46, 0x9d, 0x1c, 0xc6, 0xae, 0x09, 0xfa, 0x4c, 0xed, 0xd3, 0xeb, 0x2f,
	0xeb, 0x3f, 0x17, 0xe5, 0xa7, 0x7f, 0x6c, 0xc3, 0xc1, 0xa7, 0x98, 0xf1, 0x98, 0xc4, 0x19, 0xd3,
	0xa4, 0x3d, 0x84, 0x9d, 0x79, 0x9c, 0x31, 0x4c, 0x89, 0x8f, 0xc9, 0x35, 0xcd, 0xd5, 0xdd, 0xf5,
	0xfa, 0x32, 0xf6, 0x8c, 0x5c, 0x53, 0x74, 0x05, 0xf7, 0x18, 0x0f, 0x38, 0x0e, 0xfd, 0x44, 0x01,
	0x8c, 0x3a, 0xf9, 0x71, 0x7c, 0xe0, 0x34, 0xf8, 0xc7, 0x69, 0xa0, 0x71, 0x2e, 0x73, 0x00, 0x95,
	0xf1, 0xf6, 0x99, 0xf1, 0xcc, 0x50, 0x06, 0xa3, 0x68, 0x41, 0x82, 0x29, 0x0e, 0xfd, 0x20, 0xe4,
	0x78, 0x1e, 0x6b, 0x5c, 0xdd, 0x9c, 0xeb, 0xc3, 0xb5, 0xb9, 0x2e, 0x04, 0x50, 0x41, 0x36, 0x94,
	0xc8, 0x4f, 0x73, 0xe0, 0x92, 0x93, 0xc3, 0xb1, 0xe2, 0xfc, 0x36, 0xc8, 0xa6, 0x98, 0x4c, 0x34,
	0xd2, 0x5e, 0x4b, 0xd2, 0x23, 0x09, 0xfd, 0x85, 0x40, 0x2e, 0x59, 0xe7, 0x60, 0x2b, 0xd6, 0x28,
	0x0b, 0x30, 0x31, 0x69, 0xb7, 0x5a, 0xd2, 0xaa, 0x53, 0xbc, 0x90, 0xd0, 0xc5, 0x1a, 0xfb, 0xa5,
	0x05, 0x7b, 0x66, 0x17, 0xd0, 0x18, 0x5e, 0x53, 0xcc, 0xd2, 0x95, 0x43, 0x45, 0x9c, 0xe2, 0xa5,
	0x11, 0x0b, 0xd8, 0xa2, 0xae, 0xa5, 0x0d, 0xed, 0xdf, 0x2d, 0xd8, 0xaf, 0x68, 0x5e, 0xc7, 0x82,
	0xba, 0xd2, 0xce, 0x2d, 0x95, 0x76, 0x37, 0x1b, 0x98, 0x5f, 0xb7, 0x00, 0x9d, 0x27, 0x33, 0xc6,
	0x37, 0x9e, 0x97, 0xaf, 0x41, 0xda, 0xdb, 0x0f, 0xe5, 0x7a, 0x39, 0x2e, 0xef, 0x37, 0xb6, 0xb5,
	0x4e, 0x22, 0xa7, 0x45, 0x26, 0xbc, 0x3d, 0xa6, 0x3f, 0x32, 0x44, 0xe0, 0xa8, 0x32, 0x2b, 0x05,
	0x8f, 0x18, 0x95, 0x27, 0xeb, 0xf2, 0xc8, 0x4e, 0x28, 0xa2, 0x43, 0x63, 0x50, 0x0a, 0xbe, 0xb4,
	0x9c, 0x4d, 0x35, 0x27, 0x05, 0x61, 0xaf, 0x15, 0xe1, 0xd0, 0x1c, 0x12, 0xb5, 0xc0, 0xfe, 0x1e,
	0x76, 0x8d, 0x23, 0x40, 0x2e, 0xdc, 0x91, 0x94, 0xd2, 0xa8, 0x87, 0x66, 0xfb, 0x15, 0xa0, 0xaa,
	0x6a, 0x6b, 0xd3, 0xdf, 0x2c, 0xd8, 0x33, 0xb5, 0xae, 0xd3, 0x78, 0x4d, 0x65, 0xe7, 0x56, 0x2a,
	0x37, 0xb4, 0xe8, 0xdf, 0x3d, 0xb8, 0xe7, 0xd1, 0x19, 0x8f, 0x75, 0x83, 0x62, 0x18, 0x48, 0xf7,
	0x65, 0xcb, 0x94, 0xaf, 0x2e, 0xb0, 0x9b, 0xde, 0xd8, 0x55, 0x10, 0x69, 0xc0, 0x3c, 0x2c, 0xa2,
	0x1e, 0x62, 0xd5, 0x10, 0x43, 0x09, 0x28, 0xc7, 0x54, 0xb8, 0x6e, 0x7a, 0x63, 0xd7, 0xb8, 0xe4,
	0x39, 0xeb, 0x64, 0x07, 0x51, 0x2d, 0xc6, 0xec, 0x9f, 0x2c, 0xb8, 0x5f, 0xd3, 0x85, 0xce, 0x61,
	0x47, 0xe7, 0x96, 0xf6, 0x38, 0x31, 0x0f, 0x5e, 0x5b, 0x30, 0xcb, 0x02, 0x8e, 0x29, 0xf1, 0xfa,
	0x99, 0x06, 0xd2, 0xd2, 0x2d, 0x7f, 0x59, 0x80, 0xea, 0xbb, 0x58, 0xc7, 0x31, 0x55, 0xf5, 0x9d,
	0x57, 0xa1, 0x7e, 0x43, 0x17, 0xfd, 0xbb, 0x05, 0xc3, 0xcb, 0x90, 0xa6, 0x71, 0x54, 0xf3, 0xd2,
	0x4b, 0x0b, 0x5e, 0xc7, 0x24, 0xc1, 0x24, 0xf6, 0x59, 0x5e, 0x51, 0xe9, 0xb3, 0xf8, 0x28, 0xba,
	0x68, 0xec, 0x73, 0x33, 0xa4, 0xf3, 0x2c, 0x87, 0xd3, 0x92, 0xb2, 0xbd, 0xde, 0x08, 0xaf, 0xc8,
	0xa0, 0x1f, 0x2c, 0x78, 0xa0, 0x7c, 0xd6, 0x28, 0x43, 0x58, 0xfb, 0x93, 0x4d, 0x64, 0xc8, 0x76,
	0x35, 0xe8, 0x50, 0xdf, 0x04, 0xf5, 0x94, 0xfd, 0x8f, 0x05, 0xa3, 0x55, 0xfa, 0x11, 0x82, 0x1e,
	0x09, 0xa6, 0xb1, 0xec, 0x72, 0xfe, 0x1b, 0x7d, 0x09, 0x83, 0x1b, 0x04, 0xbf, 0x6d, 0xb6, 0xb9,
	0x86, 0xa9, 0x9a, 0x8d, 0x58, 0x9d, 0xad, 0x5d, 0xcf, 0xed, 0xff, 0x2c, 0x38, 0x5e, 0x79, 0x04,
	0x8d, 0x5b, 0xa9, 0x9a, 0xb9, 0x53, 0x37, 0xf3, 0xaa, 0xdd, 0x76, 0x5f, 0xf9, 0x6e, 0x7b, 0x9b,
	0x39, 0xfc, 0x97, 0x2d, 0xb8, 0x7f, 0x19, 0x87, 0x59, 0xcc, 0x75, 0x73, 0x7f, 0x05, 0xf2, 0x62,
	0xf5, 0x99, 0xc8, 0x49, 0x3b, 0x3f, 0x6e, 0xf6, 0x51, 0x75, 0xbd, 0x7c, 0x47, 0x8a, 0xb8, 0xb7,
	0xcb, 0xb4, 0x27, 0x86, 0xbe, 0x81, 0x61, 0xe5, 0x8a, 0x56, 0x1c, 0xa2, 0xf5, 0xef, 0xad, 0xc9,
	0xa1, 0x7a, 0x24, 0x48, 0x06, 0xc6, 0xfd, 0xac, 0xb8, 0x92, 0xf2, 0x73, 0x40, 0x5d, 0xcf, 0x8a,
	0xac, 0xdb, 0x82, 0xec, 0xd0, 0xbc, 0x9b, 0x65, 0xb9, 0xfd, 0xa7, 0x05, 0xbb, 0x46, 0xe1, 0x6d,
	0xdd, 0xd2, 0xce, 0xc1, 0xe8, 0x5d, 0xd8, 0x16, 0xbb, 0x94, 0x66, 0x38, 0x36, 0xed, 0xb5, 0xfc,
	0xd7, 0x2a, 0xb7, 0xe8, 0xc9, 0x42, 0xfb, 0x47, 0x0b, 0x76, 0xf4, 0xa6, 0x35, 0x2a, 0x6f, 0x77,
	0x15, 0x68, 0xb2, 0xba, 0x6b, 0xca, 0x3a, 0x7b, 0x02, 0x0f, 0x31, 0x15, 0x65, 0x69, 0x46, 0xbf,
	0x5b, 0x34, 0x75, 0xeb, 0x6c, 0xbf, 0xec, 0xd3, 0xf3, 0xa5, 0x84, 0xe7, 0xd6, 0xd5, 0x76, 0xae,
	0xe5, 0xf1, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x99, 0x66, 0xeb, 0xc5, 0xeb, 0x0f, 0x00, 0x00,
}
