// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/config/filter/http/transcoder/v2/transcoder.proto

package v2

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GrpcJsonTranscoder struct {
	// Types that are valid to be assigned to DescriptorSet:
	//	*GrpcJsonTranscoder_ProtoDescriptor
	//	*GrpcJsonTranscoder_ProtoDescriptorBin
	DescriptorSet isGrpcJsonTranscoder_DescriptorSet `protobuf_oneof:"descriptor_set"`
	// A list of strings that
	// supplies the fully qualified service names (i.e. "package_name.service_name") that
	// the transcoder will translate. If the service name doesn't exist in ``proto_descriptor``,
	// Envoy will fail at startup. The ``proto_descriptor`` may contain more services than
	// the service names specified here, but they won't be translated.
	Services []string `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	// Control options for response JSON. These options are passed directly to
	// `JsonPrintOptions <https://developers.google.com/protocol-buffers/docs/reference/cpp/
	// google.protobuf.util.json_util#JsonPrintOptions>`_.
	PrintOptions *GrpcJsonTranscoder_PrintOptions `protobuf:"bytes,3,opt,name=print_options,json=printOptions,proto3" json:"print_options,omitempty"`
	// Whether to keep the incoming request route after the outgoing headers have been transformed to
	// the match the upstream gRPC service. Note: This means that routes for gRPC services that are
	// not transcoded cannot be used in combination with *match_incoming_request_route*.
	MatchIncomingRequestRoute bool `protobuf:"varint,5,opt,name=match_incoming_request_route,json=matchIncomingRequestRoute,proto3" json:"match_incoming_request_route,omitempty"`
	// A list of query parameters to be ignored for transcoding method mapping.
	// By default, the transcoder filter will not transcode a request if there are any
	// unknown/invalid query parameters.
	//
	// Example :
	//
	// .. code-block:: proto
	//
	//     service Bookstore {
	//       rpc GetShelf(GetShelfRequest) returns (Shelf) {
	//         option (google.api.http) = {
	//           get: "/shelves/{shelf}"
	//         };
	//       }
	//     }
	//
	//     message GetShelfRequest {
	//       int64 shelf = 1;
	//     }
	//
	//     message Shelf {}
	//
	// The request ``/shelves/100?foo=bar`` will not be mapped to ``GetShelf``` because variable
	// binding for ``foo`` is not defined. Adding ``foo`` to ``ignored_query_parameters`` will allow
	// the same request to be mapped to ``GetShelf``.
	IgnoredQueryParameters []string `protobuf:"bytes,6,rep,name=ignored_query_parameters,json=ignoredQueryParameters,proto3" json:"ignored_query_parameters,omitempty"`
	// Whether to route methods without the ``google.api.http`` option.
	//
	// Example :
	//
	// .. code-block:: proto
	//
	//     package bookstore;
	//
	//     service Bookstore {
	//       rpc GetShelf(GetShelfRequest) returns (Shelf) {}
	//     }
	//
	//     message GetShelfRequest {
	//       int64 shelf = 1;
	//     }
	//
	//     message Shelf {}
	//
	// The client could ``post`` a json body ``{"shelf": 1234}`` with the path of
	// ``/bookstore.Bookstore/GetShelfRequest`` to call ``GetShelfRequest``.
	AutoMapping bool `protobuf:"varint,7,opt,name=auto_mapping,json=autoMapping,proto3" json:"auto_mapping,omitempty"`
	// Whether to ignore query parameters that cannot be mapped to a corresponding
	// protobuf field. Use this if you cannot control the query parameters and do
	// not know them beforehand. Otherwise use ``ignored_query_parameters``.
	// Defaults to false.
	IgnoreUnknownQueryParameters bool     `protobuf:"varint,8,opt,name=ignore_unknown_query_parameters,json=ignoreUnknownQueryParameters,proto3" json:"ignore_unknown_query_parameters,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	XXX_unrecognized             []byte   `json:"-"`
	XXX_sizecache                int32    `json:"-"`
}

func (m *GrpcJsonTranscoder) Reset()         { *m = GrpcJsonTranscoder{} }
func (m *GrpcJsonTranscoder) String() string { return proto.CompactTextString(m) }
func (*GrpcJsonTranscoder) ProtoMessage()    {}
func (*GrpcJsonTranscoder) Descriptor() ([]byte, []int) {
	return fileDescriptor_540f2f6de8b0585c, []int{0}
}

func (m *GrpcJsonTranscoder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcJsonTranscoder.Unmarshal(m, b)
}
func (m *GrpcJsonTranscoder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcJsonTranscoder.Marshal(b, m, deterministic)
}
func (m *GrpcJsonTranscoder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcJsonTranscoder.Merge(m, src)
}
func (m *GrpcJsonTranscoder) XXX_Size() int {
	return xxx_messageInfo_GrpcJsonTranscoder.Size(m)
}
func (m *GrpcJsonTranscoder) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcJsonTranscoder.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcJsonTranscoder proto.InternalMessageInfo

type isGrpcJsonTranscoder_DescriptorSet interface {
	isGrpcJsonTranscoder_DescriptorSet()
}

type GrpcJsonTranscoder_ProtoDescriptor struct {
	ProtoDescriptor string `protobuf:"bytes,1,opt,name=proto_descriptor,json=protoDescriptor,proto3,oneof"`
}

type GrpcJsonTranscoder_ProtoDescriptorBin struct {
	ProtoDescriptorBin []byte `protobuf:"bytes,4,opt,name=proto_descriptor_bin,json=protoDescriptorBin,proto3,oneof"`
}

func (*GrpcJsonTranscoder_ProtoDescriptor) isGrpcJsonTranscoder_DescriptorSet() {}

func (*GrpcJsonTranscoder_ProtoDescriptorBin) isGrpcJsonTranscoder_DescriptorSet() {}

func (m *GrpcJsonTranscoder) GetDescriptorSet() isGrpcJsonTranscoder_DescriptorSet {
	if m != nil {
		return m.DescriptorSet
	}
	return nil
}

func (m *GrpcJsonTranscoder) GetProtoDescriptor() string {
	if x, ok := m.GetDescriptorSet().(*GrpcJsonTranscoder_ProtoDescriptor); ok {
		return x.ProtoDescriptor
	}
	return ""
}

func (m *GrpcJsonTranscoder) GetProtoDescriptorBin() []byte {
	if x, ok := m.GetDescriptorSet().(*GrpcJsonTranscoder_ProtoDescriptorBin); ok {
		return x.ProtoDescriptorBin
	}
	return nil
}

func (m *GrpcJsonTranscoder) GetServices() []string {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *GrpcJsonTranscoder) GetPrintOptions() *GrpcJsonTranscoder_PrintOptions {
	if m != nil {
		return m.PrintOptions
	}
	return nil
}

func (m *GrpcJsonTranscoder) GetMatchIncomingRequestRoute() bool {
	if m != nil {
		return m.MatchIncomingRequestRoute
	}
	return false
}

func (m *GrpcJsonTranscoder) GetIgnoredQueryParameters() []string {
	if m != nil {
		return m.IgnoredQueryParameters
	}
	return nil
}

func (m *GrpcJsonTranscoder) GetAutoMapping() bool {
	if m != nil {
		return m.AutoMapping
	}
	return false
}

func (m *GrpcJsonTranscoder) GetIgnoreUnknownQueryParameters() bool {
	if m != nil {
		return m.IgnoreUnknownQueryParameters
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GrpcJsonTranscoder) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GrpcJsonTranscoder_ProtoDescriptor)(nil),
		(*GrpcJsonTranscoder_ProtoDescriptorBin)(nil),
	}
}

type GrpcJsonTranscoder_PrintOptions struct {
	// Whether to add spaces, line breaks and indentation to make the JSON
	// output easy to read. Defaults to false.
	AddWhitespace bool `protobuf:"varint,1,opt,name=add_whitespace,json=addWhitespace,proto3" json:"add_whitespace,omitempty"`
	// Whether to always print primitive fields. By default primitive
	// fields with default values will be omitted in JSON output. For
	// example, an int32 field set to 0 will be omitted. Setting this flag to
	// true will override the default behavior and print primitive fields
	// regardless of their values. Defaults to false.
	AlwaysPrintPrimitiveFields bool `protobuf:"varint,2,opt,name=always_print_primitive_fields,json=alwaysPrintPrimitiveFields,proto3" json:"always_print_primitive_fields,omitempty"`
	// Whether to always print enums as ints. By default they are rendered
	// as strings. Defaults to false.
	AlwaysPrintEnumsAsInts bool `protobuf:"varint,3,opt,name=always_print_enums_as_ints,json=alwaysPrintEnumsAsInts,proto3" json:"always_print_enums_as_ints,omitempty"`
	// Whether to preserve proto field names. By default protobuf will
	// generate JSON field names using the ``json_name`` option, or lower camel case,
	// in that order. Setting this flag will preserve the original field names. Defaults to false.
	PreserveProtoFieldNames bool     `protobuf:"varint,4,opt,name=preserve_proto_field_names,json=preserveProtoFieldNames,proto3" json:"preserve_proto_field_names,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *GrpcJsonTranscoder_PrintOptions) Reset()         { *m = GrpcJsonTranscoder_PrintOptions{} }
func (m *GrpcJsonTranscoder_PrintOptions) String() string { return proto.CompactTextString(m) }
func (*GrpcJsonTranscoder_PrintOptions) ProtoMessage()    {}
func (*GrpcJsonTranscoder_PrintOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_540f2f6de8b0585c, []int{0, 0}
}

func (m *GrpcJsonTranscoder_PrintOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcJsonTranscoder_PrintOptions.Unmarshal(m, b)
}
func (m *GrpcJsonTranscoder_PrintOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcJsonTranscoder_PrintOptions.Marshal(b, m, deterministic)
}
func (m *GrpcJsonTranscoder_PrintOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcJsonTranscoder_PrintOptions.Merge(m, src)
}
func (m *GrpcJsonTranscoder_PrintOptions) XXX_Size() int {
	return xxx_messageInfo_GrpcJsonTranscoder_PrintOptions.Size(m)
}
func (m *GrpcJsonTranscoder_PrintOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcJsonTranscoder_PrintOptions.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcJsonTranscoder_PrintOptions proto.InternalMessageInfo

func (m *GrpcJsonTranscoder_PrintOptions) GetAddWhitespace() bool {
	if m != nil {
		return m.AddWhitespace
	}
	return false
}

func (m *GrpcJsonTranscoder_PrintOptions) GetAlwaysPrintPrimitiveFields() bool {
	if m != nil {
		return m.AlwaysPrintPrimitiveFields
	}
	return false
}

func (m *GrpcJsonTranscoder_PrintOptions) GetAlwaysPrintEnumsAsInts() bool {
	if m != nil {
		return m.AlwaysPrintEnumsAsInts
	}
	return false
}

func (m *GrpcJsonTranscoder_PrintOptions) GetPreserveProtoFieldNames() bool {
	if m != nil {
		return m.PreserveProtoFieldNames
	}
	return false
}

func init() {
	proto.RegisterType((*GrpcJsonTranscoder)(nil), "envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder")
	proto.RegisterType((*GrpcJsonTranscoder_PrintOptions)(nil), "envoy.config.filter.http.transcoder.v2.GrpcJsonTranscoder.PrintOptions")
}

func init() {
	proto.RegisterFile("envoy/config/filter/http/transcoder/v2/transcoder.proto", fileDescriptor_540f2f6de8b0585c)
}

var fileDescriptor_540f2f6de8b0585c = []byte{
	// 549 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xd1, 0x6a, 0x13, 0x41,
	0x18, 0x85, 0xbb, 0x8d, 0xa9, 0xdb, 0x69, 0xda, 0xca, 0x20, 0xed, 0x1a, 0x2a, 0x46, 0xc1, 0x12,
	0x10, 0x76, 0x21, 0x0a, 0x8a, 0x5e, 0x48, 0x83, 0xb5, 0xad, 0x50, 0x8d, 0x8b, 0x22, 0x78, 0x33,
	0x4c, 0x77, 0xff, 0x24, 0x83, 0xd9, 0x99, 0xe9, 0xcc, 0xec, 0xc6, 0xbc, 0x86, 0x4f, 0x23, 0x5e,
	0xf5, 0x75, 0x7a, 0xe9, 0x03, 0x08, 0x32, 0x33, 0x4d, 0x5c, 0xd3, 0x9b, 0xde, 0x65, 0xe6, 0x7c,
	0xe7, 0x3f, 0x99, 0xfd, 0x0f, 0x7a, 0x0e, 0xbc, 0x12, 0xb3, 0x24, 0x13, 0x7c, 0xc8, 0x46, 0xc9,
	0x90, 0x4d, 0x0c, 0xa8, 0x64, 0x6c, 0x8c, 0x4c, 0x8c, 0xa2, 0x5c, 0x67, 0x22, 0x07, 0x95, 0x54,
	0xbd, 0xda, 0x29, 0x96, 0x4a, 0x18, 0x81, 0xf7, 0x9d, 0x31, 0xf6, 0xc6, 0xd8, 0x1b, 0x63, 0x6b,
	0x8c, 0x6b, 0x68, 0xd5, 0x6b, 0xef, 0x56, 0x74, 0xc2, 0x72, 0x6a, 0x20, 0x99, 0xff, 0xf0, 0x03,
	0x1e, 0xfd, 0x69, 0x22, 0x7c, 0xa4, 0x64, 0xf6, 0x4e, 0x0b, 0xfe, 0x69, 0x61, 0xc1, 0x4f, 0xd0,
	0x1d, 0xa7, 0x93, 0x1c, 0x74, 0xa6, 0x98, 0x34, 0x42, 0x45, 0x41, 0x27, 0xe8, 0xae, 0x1f, 0xaf,
	0xa4, 0xdb, 0x4e, 0x79, 0xb3, 0x10, 0x70, 0x0f, 0xdd, 0x5d, 0x86, 0xc9, 0x19, 0xe3, 0xd1, 0xad,
	0x4e, 0xd0, 0x6d, 0x1d, 0xaf, 0xa4, 0x78, 0xc9, 0xd0, 0x67, 0x1c, 0xef, 0xa3, 0x50, 0x83, 0xaa,
	0x58, 0x06, 0x3a, 0x5a, 0xed, 0x34, 0xba, 0xeb, 0x7d, 0xf4, 0xeb, 0xf2, 0xa2, 0xd1, 0xfc, 0x11,
	0xac, 0x86, 0x41, 0xba, 0xd0, 0xf0, 0x04, 0x6d, 0x4a, 0xc5, 0xb8, 0x21, 0x42, 0x1a, 0x26, 0xb8,
	0x8e, 0x1a, 0x9d, 0xa0, 0xbb, 0xd1, 0x3b, 0x8a, 0x6f, 0xf6, 0xf0, 0xf8, 0xfa, 0xdb, 0xe2, 0x81,
	0x9d, 0xf7, 0xc1, 0x8f, 0x4b, 0x5b, 0xb2, 0x76, 0xc2, 0xaf, 0xd1, 0x5e, 0x41, 0x4d, 0x36, 0x26,
	0x8c, 0x67, 0xa2, 0x60, 0x7c, 0x44, 0x14, 0x9c, 0x97, 0xa0, 0x0d, 0x51, 0xa2, 0x34, 0x10, 0x35,
	0x3b, 0x41, 0x37, 0x4c, 0xef, 0x39, 0xe6, 0xe4, 0x0a, 0x49, 0x3d, 0x91, 0x5a, 0x00, 0xbf, 0x40,
	0x11, 0x1b, 0x71, 0xa1, 0x20, 0x27, 0xe7, 0x25, 0xa8, 0x19, 0x91, 0x54, 0xd1, 0x02, 0x0c, 0x28,
	0x1d, 0xad, 0xd9, 0x67, 0xa6, 0x3b, 0x57, 0xfa, 0x47, 0x2b, 0x0f, 0x16, 0x2a, 0x7e, 0x88, 0x5a,
	0xb4, 0x34, 0x82, 0x14, 0x54, 0x4a, 0xc6, 0x47, 0xd1, 0x6d, 0x17, 0xb5, 0x61, 0xef, 0x4e, 0xfd,
	0x15, 0x3e, 0x44, 0x0f, 0xbc, 0x99, 0x94, 0xfc, 0x1b, 0x17, 0x53, 0x7e, 0x3d, 0x23, 0x74, 0xae,
	0x3d, 0x8f, 0x7d, 0xf6, 0xd4, 0x52, 0x52, 0xfb, 0x77, 0x80, 0x5a, 0xf5, 0x6f, 0x80, 0x1f, 0xa3,
	0x2d, 0x9a, 0xe7, 0x64, 0x3a, 0x66, 0x06, 0xb4, 0xa4, 0x19, 0xb8, 0x55, 0x87, 0xe9, 0x26, 0xcd,
	0xf3, 0x2f, 0x8b, 0x4b, 0x7c, 0x80, 0xee, 0xd3, 0xc9, 0x94, 0xce, 0x34, 0xf1, 0x1b, 0x91, 0x8a,
	0x15, 0xcc, 0xb0, 0x0a, 0xc8, 0x90, 0xc1, 0x24, 0xb7, 0x7b, 0xb4, 0xae, 0xb6, 0x87, 0x5c, 0xc2,
	0x60, 0x8e, 0xbc, 0x75, 0x04, 0x7e, 0x89, 0xda, 0xff, 0x8d, 0x00, 0x5e, 0x16, 0x9a, 0x50, 0x4d,
	0x18, 0x37, 0x7e, 0xb5, 0x61, 0xba, 0x53, 0xf3, 0x1f, 0x5a, 0xfd, 0x40, 0x9f, 0x70, 0xa3, 0xf1,
	0x2b, 0xd4, 0x96, 0x0a, 0x6c, 0x31, 0x80, 0xf8, 0xba, 0xb9, 0x58, 0xc2, 0x69, 0x01, 0xda, 0x75,
	0x2d, 0x4c, 0x77, 0xe7, 0xc4, 0xc0, 0x02, 0x2e, 0xf4, 0xbd, 0x95, 0xfb, 0xbb, 0x68, 0xab, 0x56,
	0x4e, 0x0d, 0x06, 0x37, 0x7f, 0x5e, 0x5e, 0x34, 0x82, 0xfe, 0x29, 0x7a, 0xc6, 0x84, 0x2f, 0x93,
	0x54, 0xe2, 0xfb, 0xec, 0x86, 0xbd, 0xea, 0x6f, 0xff, 0x2b, 0x94, 0xcb, 0x1a, 0x04, 0x5f, 0x57,
	0xab, 0xde, 0xd9, 0x9a, 0xfb, 0x67, 0x4f, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x83, 0x68,
	0x5c, 0xd1, 0x03, 0x00, 0x00,
}
