// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/config/filter/network/thrift_proxy/v2alpha1/route.proto

package v2

import (
	fmt "fmt"
	core "github.com/envoyproxy/go-control-plane/envoy/api/v2/core"
	route "github.com/envoyproxy/go-control-plane/envoy/api/v2/route"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// [#comment:next free field: 3]
type RouteConfiguration struct {
	// The name of the route configuration. Reserved for future use in asynchronous route discovery.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The list of routes that will be matched, in order, against incoming requests. The first route
	// that matches will be used.
	Routes               []*Route `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteConfiguration) Reset()         { *m = RouteConfiguration{} }
func (m *RouteConfiguration) String() string { return proto.CompactTextString(m) }
func (*RouteConfiguration) ProtoMessage()    {}
func (*RouteConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_3de6ac0eae6369f5, []int{0}
}

func (m *RouteConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteConfiguration.Unmarshal(m, b)
}
func (m *RouteConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteConfiguration.Marshal(b, m, deterministic)
}
func (m *RouteConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteConfiguration.Merge(m, src)
}
func (m *RouteConfiguration) XXX_Size() int {
	return xxx_messageInfo_RouteConfiguration.Size(m)
}
func (m *RouteConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_RouteConfiguration proto.InternalMessageInfo

func (m *RouteConfiguration) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RouteConfiguration) GetRoutes() []*Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

// [#comment:next free field: 3]
type Route struct {
	// Route matching parameters.
	Match *RouteMatch `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	// Route request to some upstream cluster.
	Route                *RouteAction `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}
func (*Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_3de6ac0eae6369f5, []int{1}
}

func (m *Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route.Unmarshal(m, b)
}
func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route.Marshal(b, m, deterministic)
}
func (m *Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route.Merge(m, src)
}
func (m *Route) XXX_Size() int {
	return xxx_messageInfo_Route.Size(m)
}
func (m *Route) XXX_DiscardUnknown() {
	xxx_messageInfo_Route.DiscardUnknown(m)
}

var xxx_messageInfo_Route proto.InternalMessageInfo

func (m *Route) GetMatch() *RouteMatch {
	if m != nil {
		return m.Match
	}
	return nil
}

func (m *Route) GetRoute() *RouteAction {
	if m != nil {
		return m.Route
	}
	return nil
}

// [#comment:next free field: 5]
type RouteMatch struct {
	// Types that are valid to be assigned to MatchSpecifier:
	//	*RouteMatch_MethodName
	//	*RouteMatch_ServiceName
	MatchSpecifier isRouteMatch_MatchSpecifier `protobuf_oneof:"match_specifier"`
	// Inverts whatever matching is done in the :ref:`method_name
	// <envoy_api_field_config.filter.network.thrift_proxy.v2alpha1.RouteMatch.method_name>` or
	// :ref:`service_name
	// <envoy_api_field_config.filter.network.thrift_proxy.v2alpha1.RouteMatch.service_name>` fields.
	// Cannot be combined with wildcard matching as that would result in routes never being matched.
	//
	// .. note::
	//
	//   This does not invert matching done as part of the :ref:`headers field
	//   <envoy_api_field_config.filter.network.thrift_proxy.v2alpha1.RouteMatch.headers>` field. To
	//   invert header matching, see :ref:`invert_match
	//   <envoy_api_field_route.HeaderMatcher.invert_match>`.
	Invert bool `protobuf:"varint,3,opt,name=invert,proto3" json:"invert,omitempty"`
	// Specifies a set of headers that the route should match on. The router will check the request’s
	// headers against all the specified headers in the route config. A match will happen if all the
	// headers in the route are present in the request with the same values (or based on presence if
	// the value field is not in the config). Note that this only applies for Thrift transports and/or
	// protocols that support headers.
	Headers              []*route.HeaderMatcher `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RouteMatch) Reset()         { *m = RouteMatch{} }
func (m *RouteMatch) String() string { return proto.CompactTextString(m) }
func (*RouteMatch) ProtoMessage()    {}
func (*RouteMatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_3de6ac0eae6369f5, []int{2}
}

func (m *RouteMatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteMatch.Unmarshal(m, b)
}
func (m *RouteMatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteMatch.Marshal(b, m, deterministic)
}
func (m *RouteMatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteMatch.Merge(m, src)
}
func (m *RouteMatch) XXX_Size() int {
	return xxx_messageInfo_RouteMatch.Size(m)
}
func (m *RouteMatch) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteMatch.DiscardUnknown(m)
}

var xxx_messageInfo_RouteMatch proto.InternalMessageInfo

type isRouteMatch_MatchSpecifier interface {
	isRouteMatch_MatchSpecifier()
}

type RouteMatch_MethodName struct {
	MethodName string `protobuf:"bytes,1,opt,name=method_name,json=methodName,proto3,oneof"`
}

type RouteMatch_ServiceName struct {
	ServiceName string `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3,oneof"`
}

func (*RouteMatch_MethodName) isRouteMatch_MatchSpecifier() {}

func (*RouteMatch_ServiceName) isRouteMatch_MatchSpecifier() {}

func (m *RouteMatch) GetMatchSpecifier() isRouteMatch_MatchSpecifier {
	if m != nil {
		return m.MatchSpecifier
	}
	return nil
}

func (m *RouteMatch) GetMethodName() string {
	if x, ok := m.GetMatchSpecifier().(*RouteMatch_MethodName); ok {
		return x.MethodName
	}
	return ""
}

func (m *RouteMatch) GetServiceName() string {
	if x, ok := m.GetMatchSpecifier().(*RouteMatch_ServiceName); ok {
		return x.ServiceName
	}
	return ""
}

func (m *RouteMatch) GetInvert() bool {
	if m != nil {
		return m.Invert
	}
	return false
}

func (m *RouteMatch) GetHeaders() []*route.HeaderMatcher {
	if m != nil {
		return m.Headers
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RouteMatch) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RouteMatch_MethodName)(nil),
		(*RouteMatch_ServiceName)(nil),
	}
}

// [#comment:next free field: 5]
type RouteAction struct {
	// Types that are valid to be assigned to ClusterSpecifier:
	//	*RouteAction_Cluster
	//	*RouteAction_WeightedClusters
	ClusterSpecifier isRouteAction_ClusterSpecifier `protobuf_oneof:"cluster_specifier"`
	// Optional endpoint metadata match criteria used by the subset load balancer. Only endpoints in
	// the upstream cluster with metadata matching what is set in this field will be considered.
	// Note that this will be merged with what's provided in :ref: `WeightedCluster.MetadataMatch
	// <envoy_api_field_config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight.metadata_match>`,
	// with values there taking precedence. Keys and values should be provided under the "envoy.lb"
	// metadata key.
	MetadataMatch *core.Metadata `protobuf:"bytes,3,opt,name=metadata_match,json=metadataMatch,proto3" json:"metadata_match,omitempty"`
	// Specifies a set of rate limit configurations that could be applied to the route.
	// N.B. Thrift service or method name matching can be achieved by specifying a RequestHeaders
	// action with the header name ":method-name".
	RateLimits           []*route.RateLimit `protobuf:"bytes,4,rep,name=rate_limits,json=rateLimits,proto3" json:"rate_limits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RouteAction) Reset()         { *m = RouteAction{} }
func (m *RouteAction) String() string { return proto.CompactTextString(m) }
func (*RouteAction) ProtoMessage()    {}
func (*RouteAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_3de6ac0eae6369f5, []int{3}
}

func (m *RouteAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteAction.Unmarshal(m, b)
}
func (m *RouteAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteAction.Marshal(b, m, deterministic)
}
func (m *RouteAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteAction.Merge(m, src)
}
func (m *RouteAction) XXX_Size() int {
	return xxx_messageInfo_RouteAction.Size(m)
}
func (m *RouteAction) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteAction.DiscardUnknown(m)
}

var xxx_messageInfo_RouteAction proto.InternalMessageInfo

type isRouteAction_ClusterSpecifier interface {
	isRouteAction_ClusterSpecifier()
}

type RouteAction_Cluster struct {
	Cluster string `protobuf:"bytes,1,opt,name=cluster,proto3,oneof"`
}

type RouteAction_WeightedClusters struct {
	WeightedClusters *WeightedCluster `protobuf:"bytes,2,opt,name=weighted_clusters,json=weightedClusters,proto3,oneof"`
}

func (*RouteAction_Cluster) isRouteAction_ClusterSpecifier() {}

func (*RouteAction_WeightedClusters) isRouteAction_ClusterSpecifier() {}

func (m *RouteAction) GetClusterSpecifier() isRouteAction_ClusterSpecifier {
	if m != nil {
		return m.ClusterSpecifier
	}
	return nil
}

func (m *RouteAction) GetCluster() string {
	if x, ok := m.GetClusterSpecifier().(*RouteAction_Cluster); ok {
		return x.Cluster
	}
	return ""
}

func (m *RouteAction) GetWeightedClusters() *WeightedCluster {
	if x, ok := m.GetClusterSpecifier().(*RouteAction_WeightedClusters); ok {
		return x.WeightedClusters
	}
	return nil
}

func (m *RouteAction) GetMetadataMatch() *core.Metadata {
	if m != nil {
		return m.MetadataMatch
	}
	return nil
}

func (m *RouteAction) GetRateLimits() []*route.RateLimit {
	if m != nil {
		return m.RateLimits
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RouteAction) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RouteAction_Cluster)(nil),
		(*RouteAction_WeightedClusters)(nil),
	}
}

// Allows for specification of multiple upstream clusters along with weights that indicate the
// percentage of traffic to be forwarded to each cluster. The router selects an upstream cluster
// based on these weights.
type WeightedCluster struct {
	// Specifies one or more upstream clusters associated with the route.
	Clusters             []*WeightedCluster_ClusterWeight `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *WeightedCluster) Reset()         { *m = WeightedCluster{} }
func (m *WeightedCluster) String() string { return proto.CompactTextString(m) }
func (*WeightedCluster) ProtoMessage()    {}
func (*WeightedCluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_3de6ac0eae6369f5, []int{4}
}

func (m *WeightedCluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeightedCluster.Unmarshal(m, b)
}
func (m *WeightedCluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeightedCluster.Marshal(b, m, deterministic)
}
func (m *WeightedCluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeightedCluster.Merge(m, src)
}
func (m *WeightedCluster) XXX_Size() int {
	return xxx_messageInfo_WeightedCluster.Size(m)
}
func (m *WeightedCluster) XXX_DiscardUnknown() {
	xxx_messageInfo_WeightedCluster.DiscardUnknown(m)
}

var xxx_messageInfo_WeightedCluster proto.InternalMessageInfo

func (m *WeightedCluster) GetClusters() []*WeightedCluster_ClusterWeight {
	if m != nil {
		return m.Clusters
	}
	return nil
}

type WeightedCluster_ClusterWeight struct {
	// Name of the upstream cluster.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// When a request matches the route, the choice of an upstream cluster is determined by its
	// weight. The sum of weights across all entries in the clusters array determines the total
	// weight.
	Weight *wrappers.UInt32Value `protobuf:"bytes,2,opt,name=weight,proto3" json:"weight,omitempty"`
	// Optional endpoint metadata match criteria used by the subset load balancer. Only endpoints in
	// the upstream cluster with metadata matching what is set in this field, combined with what's
	// provided in :ref: `RouteAction's metadata_match
	// <envoy_api_field_config.filter.network.thrift_proxy.v2alpha1.RouteAction.metadata_match>`,
	// will be considered. Values here will take precedence. Keys and values should be provided
	// under the "envoy.lb" metadata key.
	MetadataMatch        *core.Metadata `protobuf:"bytes,3,opt,name=metadata_match,json=metadataMatch,proto3" json:"metadata_match,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *WeightedCluster_ClusterWeight) Reset()         { *m = WeightedCluster_ClusterWeight{} }
func (m *WeightedCluster_ClusterWeight) String() string { return proto.CompactTextString(m) }
func (*WeightedCluster_ClusterWeight) ProtoMessage()    {}
func (*WeightedCluster_ClusterWeight) Descriptor() ([]byte, []int) {
	return fileDescriptor_3de6ac0eae6369f5, []int{4, 0}
}

func (m *WeightedCluster_ClusterWeight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeightedCluster_ClusterWeight.Unmarshal(m, b)
}
func (m *WeightedCluster_ClusterWeight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeightedCluster_ClusterWeight.Marshal(b, m, deterministic)
}
func (m *WeightedCluster_ClusterWeight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeightedCluster_ClusterWeight.Merge(m, src)
}
func (m *WeightedCluster_ClusterWeight) XXX_Size() int {
	return xxx_messageInfo_WeightedCluster_ClusterWeight.Size(m)
}
func (m *WeightedCluster_ClusterWeight) XXX_DiscardUnknown() {
	xxx_messageInfo_WeightedCluster_ClusterWeight.DiscardUnknown(m)
}

var xxx_messageInfo_WeightedCluster_ClusterWeight proto.InternalMessageInfo

func (m *WeightedCluster_ClusterWeight) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WeightedCluster_ClusterWeight) GetWeight() *wrappers.UInt32Value {
	if m != nil {
		return m.Weight
	}
	return nil
}

func (m *WeightedCluster_ClusterWeight) GetMetadataMatch() *core.Metadata {
	if m != nil {
		return m.MetadataMatch
	}
	return nil
}

func init() {
	proto.RegisterType((*RouteConfiguration)(nil), "envoy.config.filter.network.thrift_proxy.v2alpha1.RouteConfiguration")
	proto.RegisterType((*Route)(nil), "envoy.config.filter.network.thrift_proxy.v2alpha1.Route")
	proto.RegisterType((*RouteMatch)(nil), "envoy.config.filter.network.thrift_proxy.v2alpha1.RouteMatch")
	proto.RegisterType((*RouteAction)(nil), "envoy.config.filter.network.thrift_proxy.v2alpha1.RouteAction")
	proto.RegisterType((*WeightedCluster)(nil), "envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster")
	proto.RegisterType((*WeightedCluster_ClusterWeight)(nil), "envoy.config.filter.network.thrift_proxy.v2alpha1.WeightedCluster.ClusterWeight")
}

func init() {
	proto.RegisterFile("envoy/config/filter/network/thrift_proxy/v2alpha1/route.proto", fileDescriptor_3de6ac0eae6369f5)
}

var fileDescriptor_3de6ac0eae6369f5 = []byte{
	// 653 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xc1, 0x6e, 0x13, 0x3d,
	0x10, 0xae, 0x37, 0x4d, 0xda, 0x4e, 0xfe, 0xfe, 0x6d, 0x2d, 0x04, 0x51, 0x68, 0xab, 0x34, 0x08,
	0x29, 0xe2, 0xe0, 0x55, 0xd3, 0x0b, 0x12, 0x6a, 0x2b, 0xb6, 0x97, 0x20, 0x51, 0x14, 0x19, 0x01,
	0x12, 0x97, 0xe0, 0x6e, 0x9c, 0xc4, 0x62, 0xb3, 0x5e, 0xbc, 0xce, 0xa6, 0xe5, 0x11, 0x38, 0xf2,
	0x2a, 0x5c, 0x10, 0xa7, 0x22, 0x0e, 0x48, 0xbc, 0x49, 0xdf, 0x02, 0xad, 0xed, 0x6d, 0x13, 0xe0,
	0xd2, 0xc2, 0x69, 0x67, 0xc7, 0xf3, 0xcd, 0xe7, 0xef, 0x1b, 0xdb, 0xb0, 0xcf, 0xe3, 0x4c, 0x9e,
	0xf9, 0xa1, 0x8c, 0x07, 0x62, 0xe8, 0x0f, 0x44, 0xa4, 0xb9, 0xf2, 0x63, 0xae, 0xa7, 0x52, 0xbd,
	0xf5, 0xf5, 0x48, 0x89, 0x81, 0xee, 0x25, 0x4a, 0x9e, 0x9e, 0xf9, 0x59, 0x9b, 0x45, 0xc9, 0x88,
	0xed, 0xfa, 0x4a, 0x4e, 0x34, 0x27, 0x89, 0x92, 0x5a, 0xe2, 0x5d, 0x03, 0x27, 0x16, 0x4e, 0x2c,
	0x9c, 0x38, 0x38, 0x99, 0x85, 0x93, 0x02, 0x5e, 0xdf, 0xb4, 0x8c, 0x2c, 0x11, 0x7e, 0xd6, 0xf6,
	0x43, 0xa9, 0xb8, 0x7f, 0xc2, 0x52, 0xd7, 0xb0, 0xbe, 0x3d, 0xb7, 0x6a, 0xa8, 0x66, 0x09, 0xeb,
	0xdb, 0x43, 0x29, 0x87, 0x11, 0xf7, 0xcd, 0xdf, 0xc9, 0x64, 0xe0, 0x4f, 0x15, 0x4b, 0x12, 0xae,
	0x52, 0xb7, 0x7e, 0x27, 0x63, 0x91, 0xe8, 0x33, 0xcd, 0xfd, 0x22, 0x70, 0x0b, 0xb7, 0x86, 0x72,
	0x28, 0x4d, 0xe8, 0xe7, 0x91, 0xcd, 0x36, 0xdf, 0x03, 0xa6, 0x79, 0xf7, 0x23, 0x23, 0x60, 0xa2,
	0x98, 0x16, 0x32, 0xc6, 0x18, 0x16, 0x63, 0x36, 0xe6, 0x35, 0xd4, 0x40, 0xad, 0x15, 0x6a, 0x62,
	0xdc, 0x85, 0x8a, 0xd9, 0x47, 0x5a, 0xf3, 0x1a, 0xa5, 0x56, 0xb5, 0xfd, 0x90, 0x5c, 0x5b, 0x3a,
	0x31, 0x54, 0xd4, 0xf5, 0x69, 0xfe, 0x40, 0x50, 0x36, 0x19, 0xdc, 0x83, 0xf2, 0x98, 0xe9, 0x70,
	0x64, 0x08, 0xab, 0xed, 0xfd, 0x9b, 0xb6, 0x3e, 0xce, 0x9b, 0x04, 0xf0, 0xe5, 0xe2, 0xbc, 0x54,
	0xfe, 0x80, 0xbc, 0x75, 0x44, 0x6d, 0x5f, 0xfc, 0x06, 0xca, 0x86, 0xb4, 0xe6, 0x19, 0x82, 0x83,
	0x9b, 0x12, 0x3c, 0x0e, 0x73, 0x7f, 0xe6, 0x19, 0x4c, 0xe3, 0xe6, 0x37, 0x04, 0x70, 0xb5, 0x07,
	0xbc, 0x03, 0xd5, 0x31, 0xd7, 0x23, 0xd9, 0xef, 0x5d, 0x19, 0xd9, 0x59, 0xa0, 0x60, 0x93, 0xcf,
	0x72, 0x43, 0xef, 0xc1, 0x7f, 0x29, 0x57, 0x99, 0x08, 0xb9, 0xad, 0xf1, 0x5c, 0x4d, 0xd5, 0x65,
	0x4d, 0xd1, 0x6d, 0xa8, 0x88, 0x38, 0xe3, 0x4a, 0xd7, 0x4a, 0x0d, 0xd4, 0x5a, 0xa6, 0xee, 0x0f,
	0x3f, 0x82, 0xa5, 0x11, 0x67, 0x7d, 0xae, 0xd2, 0xda, 0xa2, 0x19, 0xc7, 0x8e, 0x93, 0xc4, 0x12,
	0x41, 0xb2, 0x36, 0xb1, 0x47, 0xa6, 0x63, 0x4a, 0xcc, 0x8e, 0xb8, 0xa2, 0x05, 0x22, 0xa8, 0xc1,
	0x9a, 0xb1, 0xa5, 0x97, 0x26, 0x3c, 0x14, 0x03, 0xc1, 0x15, 0x2e, 0x7f, 0xbe, 0x38, 0x2f, 0xa1,
	0xe6, 0x77, 0x0f, 0xaa, 0x33, 0x42, 0xf1, 0x7d, 0x58, 0x0a, 0xa3, 0x49, 0xaa, 0xb9, 0xb2, 0x12,
	0x82, 0x95, 0x5c, 0xf9, 0xa2, 0xf2, 0x1a, 0xa8, 0xb3, 0x40, 0x8b, 0x35, 0xfc, 0x0e, 0x36, 0xa6,
	0x5c, 0x0c, 0x47, 0x9a, 0xf7, 0x7b, 0x2e, 0x97, 0x3a, 0xab, 0x83, 0x1b, 0x58, 0xfd, 0xca, 0xf5,
	0x3a, 0xb2, 0xad, 0x3a, 0x0b, 0x74, 0x7d, 0x3a, 0x9f, 0x4a, 0x71, 0x00, 0xff, 0x8f, 0xb9, 0x66,
	0x7d, 0xa6, 0x59, 0xcf, 0x9e, 0x9d, 0x92, 0xe1, 0xbb, 0x3b, 0xef, 0x43, 0x7e, 0xbd, 0xc8, 0xb1,
	0x2b, 0xa4, 0xab, 0x05, 0xc4, 0x0e, 0xe9, 0x00, 0xaa, 0x8a, 0x69, 0xde, 0x8b, 0xc4, 0x58, 0xe8,
	0xc2, 0xc8, 0xad, 0x3f, 0x19, 0x49, 0x99, 0xe6, 0x4f, 0xf3, 0x2a, 0x0a, 0xaa, 0x08, 0xd3, 0xa0,
	0x0e, 0x1b, 0x4e, 0xed, 0xef, 0x4e, 0x7e, 0xf5, 0x60, 0xed, 0x17, 0x1d, 0xf8, 0x14, 0x96, 0x2f,
	0xdd, 0x41, 0x86, 0xac, 0xfb, 0xf7, 0xee, 0x10, 0xf7, 0xb5, 0x69, 0x77, 0x34, 0x3f, 0x22, 0x6f,
	0x19, 0xd1, 0x4b, 0xb6, 0xfa, 0x27, 0x04, 0xab, 0x73, 0x75, 0x78, 0x6b, 0xf6, 0x8a, 0xcf, 0x8c,
	0xd5, 0xdd, 0xf6, 0x43, 0xa8, 0x58, 0xcb, 0xdd, 0x18, 0x37, 0x89, 0x7d, 0x77, 0x48, 0xf1, 0xee,
	0x90, 0x17, 0x4f, 0x62, 0xbd, 0xd7, 0x7e, 0xc9, 0xa2, 0x09, 0x77, 0xf0, 0x07, 0x5e, 0x0b, 0x51,
	0x07, 0xfb, 0x17, 0xf3, 0x09, 0x9e, 0xc3, 0xa1, 0x90, 0xb6, 0xde, 0x7a, 0x70, 0x6d, 0xb3, 0x02,
	0x7b, 0x27, 0xbb, 0xf9, 0xa6, 0xbb, 0xe8, 0xb5, 0x97, 0xb5, 0x4f, 0x2a, 0x46, 0xc1, 0xde, 0xcf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x5c, 0x12, 0x89, 0xf9, 0x05, 0x00, 0x00,
}
