// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/config/filter/http/header_to_metadata/v2/header_to_metadata.proto

package v2

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Config_ValueType int32

const (
	Config_STRING Config_ValueType = 0
	Config_NUMBER Config_ValueType = 1
	// The value is a serialized `protobuf.Value
	// <https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/struct.proto#L62>`_.
	Config_PROTOBUF_VALUE Config_ValueType = 2
)

var Config_ValueType_name = map[int32]string{
	0: "STRING",
	1: "NUMBER",
	2: "PROTOBUF_VALUE",
}

var Config_ValueType_value = map[string]int32{
	"STRING":         0,
	"NUMBER":         1,
	"PROTOBUF_VALUE": 2,
}

func (x Config_ValueType) String() string {
	return proto.EnumName(Config_ValueType_name, int32(x))
}

func (Config_ValueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5891b90c2f7c1ebe, []int{0, 0}
}

// ValueEncode defines the encoding algorithm.
type Config_ValueEncode int32

const (
	// The value is not encoded.
	Config_NONE Config_ValueEncode = 0
	// The value is encoded in `Base64 <https://tools.ietf.org/html/rfc4648#section-4>`_.
	// Note: this is mostly used for STRING and PROTOBUF_VALUE to escape the
	// non-ASCII characters in the header.
	Config_BASE64 Config_ValueEncode = 1
)

var Config_ValueEncode_name = map[int32]string{
	0: "NONE",
	1: "BASE64",
}

var Config_ValueEncode_value = map[string]int32{
	"NONE":   0,
	"BASE64": 1,
}

func (x Config_ValueEncode) String() string {
	return proto.EnumName(Config_ValueEncode_name, int32(x))
}

func (Config_ValueEncode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5891b90c2f7c1ebe, []int{0, 1}
}

type Config struct {
	// The list of rules to apply to requests.
	RequestRules []*Config_Rule `protobuf:"bytes,1,rep,name=request_rules,json=requestRules,proto3" json:"request_rules,omitempty"`
	// The list of rules to apply to responses.
	ResponseRules        []*Config_Rule `protobuf:"bytes,2,rep,name=response_rules,json=responseRules,proto3" json:"response_rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_5891b90c2f7c1ebe, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetRequestRules() []*Config_Rule {
	if m != nil {
		return m.RequestRules
	}
	return nil
}

func (m *Config) GetResponseRules() []*Config_Rule {
	if m != nil {
		return m.ResponseRules
	}
	return nil
}

type Config_KeyValuePair struct {
	// The namespace — if this is empty, the filter's namespace will be used.
	MetadataNamespace string `protobuf:"bytes,1,opt,name=metadata_namespace,json=metadataNamespace,proto3" json:"metadata_namespace,omitempty"`
	// The key to use within the namespace.
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// The value to pair with the given key.
	//
	// When used for a `on_header_present` case, if value is non-empty it'll be used
	// instead of the header value. If both are empty, no metadata is added.
	//
	// When used for a `on_header_missing` case, a non-empty value must be provided
	// otherwise no metadata is added.
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// The value's type — defaults to string.
	Type Config_ValueType `protobuf:"varint,4,opt,name=type,proto3,enum=envoy.config.filter.http.header_to_metadata.v2.Config_ValueType" json:"type,omitempty"`
	// How is the value encoded, default is NONE (not encoded).
	// The value will be decoded accordingly before storing to metadata.
	Encode               Config_ValueEncode `protobuf:"varint,5,opt,name=encode,proto3,enum=envoy.config.filter.http.header_to_metadata.v2.Config_ValueEncode" json:"encode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Config_KeyValuePair) Reset()         { *m = Config_KeyValuePair{} }
func (m *Config_KeyValuePair) String() string { return proto.CompactTextString(m) }
func (*Config_KeyValuePair) ProtoMessage()    {}
func (*Config_KeyValuePair) Descriptor() ([]byte, []int) {
	return fileDescriptor_5891b90c2f7c1ebe, []int{0, 0}
}

func (m *Config_KeyValuePair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config_KeyValuePair.Unmarshal(m, b)
}
func (m *Config_KeyValuePair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config_KeyValuePair.Marshal(b, m, deterministic)
}
func (m *Config_KeyValuePair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config_KeyValuePair.Merge(m, src)
}
func (m *Config_KeyValuePair) XXX_Size() int {
	return xxx_messageInfo_Config_KeyValuePair.Size(m)
}
func (m *Config_KeyValuePair) XXX_DiscardUnknown() {
	xxx_messageInfo_Config_KeyValuePair.DiscardUnknown(m)
}

var xxx_messageInfo_Config_KeyValuePair proto.InternalMessageInfo

func (m *Config_KeyValuePair) GetMetadataNamespace() string {
	if m != nil {
		return m.MetadataNamespace
	}
	return ""
}

func (m *Config_KeyValuePair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Config_KeyValuePair) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Config_KeyValuePair) GetType() Config_ValueType {
	if m != nil {
		return m.Type
	}
	return Config_STRING
}

func (m *Config_KeyValuePair) GetEncode() Config_ValueEncode {
	if m != nil {
		return m.Encode
	}
	return Config_NONE
}

// A Rule defines what metadata to apply when a header is present or missing.
type Config_Rule struct {
	// The header that triggers this rule — required.
	Header string `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// If the header is present, apply this metadata KeyValuePair.
	//
	// If the value in the KeyValuePair is non-empty, it'll be used instead
	// of the header value.
	OnHeaderPresent *Config_KeyValuePair `protobuf:"bytes,2,opt,name=on_header_present,json=onHeaderPresent,proto3" json:"on_header_present,omitempty"`
	// If the header is not present, apply this metadata KeyValuePair.
	//
	// The value in the KeyValuePair must be set, since it'll be used in lieu
	// of the missing header value.
	OnHeaderMissing *Config_KeyValuePair `protobuf:"bytes,3,opt,name=on_header_missing,json=onHeaderMissing,proto3" json:"on_header_missing,omitempty"`
	// Whether or not to remove the header after a rule is applied.
	//
	// This prevents headers from leaking.
	Remove               bool     `protobuf:"varint,4,opt,name=remove,proto3" json:"remove,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config_Rule) Reset()         { *m = Config_Rule{} }
func (m *Config_Rule) String() string { return proto.CompactTextString(m) }
func (*Config_Rule) ProtoMessage()    {}
func (*Config_Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_5891b90c2f7c1ebe, []int{0, 1}
}

func (m *Config_Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config_Rule.Unmarshal(m, b)
}
func (m *Config_Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config_Rule.Marshal(b, m, deterministic)
}
func (m *Config_Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config_Rule.Merge(m, src)
}
func (m *Config_Rule) XXX_Size() int {
	return xxx_messageInfo_Config_Rule.Size(m)
}
func (m *Config_Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_Config_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_Config_Rule proto.InternalMessageInfo

func (m *Config_Rule) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *Config_Rule) GetOnHeaderPresent() *Config_KeyValuePair {
	if m != nil {
		return m.OnHeaderPresent
	}
	return nil
}

func (m *Config_Rule) GetOnHeaderMissing() *Config_KeyValuePair {
	if m != nil {
		return m.OnHeaderMissing
	}
	return nil
}

func (m *Config_Rule) GetRemove() bool {
	if m != nil {
		return m.Remove
	}
	return false
}

func init() {
	proto.RegisterEnum("envoy.config.filter.http.header_to_metadata.v2.Config_ValueType", Config_ValueType_name, Config_ValueType_value)
	proto.RegisterEnum("envoy.config.filter.http.header_to_metadata.v2.Config_ValueEncode", Config_ValueEncode_name, Config_ValueEncode_value)
	proto.RegisterType((*Config)(nil), "envoy.config.filter.http.header_to_metadata.v2.Config")
	proto.RegisterType((*Config_KeyValuePair)(nil), "envoy.config.filter.http.header_to_metadata.v2.Config.KeyValuePair")
	proto.RegisterType((*Config_Rule)(nil), "envoy.config.filter.http.header_to_metadata.v2.Config.Rule")
}

func init() {
	proto.RegisterFile("envoy/config/filter/http/header_to_metadata/v2/header_to_metadata.proto", fileDescriptor_5891b90c2f7c1ebe)
}

var fileDescriptor_5891b90c2f7c1ebe = []byte{
	// 495 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xb1, 0x93, 0x5a, 0xcd, 0xa4, 0x0d, 0xe9, 0x8a, 0x0f, 0x2b, 0x5c, 0x42, 0xb8, 0xe4,
	0x82, 0x2d, 0x19, 0x04, 0x07, 0x38, 0x50, 0x57, 0xa1, 0x20, 0xc8, 0x87, 0xb6, 0x4e, 0x0f, 0xe5,
	0x60, 0xb6, 0xc9, 0xb4, 0xb5, 0x70, 0xbc, 0x66, 0xbd, 0xb1, 0xf0, 0xeb, 0xc0, 0x5b, 0x70, 0xe2,
	0x75, 0x78, 0x02, 0xae, 0xc8, 0xbb, 0x36, 0x0a, 0x52, 0x2f, 0xfd, 0xb8, 0xed, 0xcc, 0xec, 0xfc,
	0xfe, 0x3b, 0xff, 0xd1, 0xc2, 0x21, 0x26, 0x39, 0x2f, 0xdc, 0x05, 0x4f, 0xce, 0xa2, 0x73, 0xf7,
	0x2c, 0x8a, 0x25, 0x0a, 0xf7, 0x42, 0xca, 0xd4, 0xbd, 0x40, 0xb6, 0x44, 0x11, 0x4a, 0x1e, 0xae,
	0x50, 0xb2, 0x25, 0x93, 0xcc, 0xcd, 0xbd, 0x4b, 0xb2, 0x4e, 0x2a, 0xb8, 0xe4, 0xc4, 0x51, 0x20,
	0x47, 0x83, 0x1c, 0x0d, 0x72, 0x4a, 0x90, 0x73, 0x49, 0x4b, 0xee, 0xf5, 0x1e, 0xe6, 0x2c, 0x8e,
	0x96, 0x4c, 0xa2, 0x5b, 0x1f, 0x34, 0x68, 0xf0, 0xc7, 0x02, 0xeb, 0x40, 0x51, 0xc8, 0x67, 0xd8,
	0x15, 0xf8, 0x75, 0x8d, 0x99, 0x0c, 0xc5, 0x3a, 0xc6, 0xcc, 0x36, 0xfa, 0x8d, 0x61, 0xdb, 0x7b,
	0x75, 0x45, 0x2d, 0x47, 0xe3, 0x1c, 0xba, 0x8e, 0x91, 0xee, 0x54, 0xc4, 0x32, 0xc8, 0xc8, 0x29,
	0x74, 0x04, 0x66, 0x29, 0x4f, 0x32, 0xac, 0x24, 0xcc, 0x9b, 0x4b, 0xec, 0xd6, 0x48, 0xa5, 0xd1,
	0xfb, 0x6e, 0xc2, 0xce, 0x07, 0x2c, 0x8e, 0x59, 0xbc, 0xc6, 0x19, 0x8b, 0x04, 0x79, 0x0a, 0xa4,
	0x6e, 0x0d, 0x13, 0xb6, 0xc2, 0x2c, 0x65, 0x0b, 0xb4, 0x8d, 0xbe, 0x31, 0x6c, 0xd1, 0xbd, 0xba,
	0x32, 0xa9, 0x0b, 0xe4, 0x11, 0x34, 0xbe, 0x60, 0x61, 0x9b, 0x65, 0xdd, 0x6f, 0xfd, 0xfc, 0xfd,
	0xab, 0xd1, 0x14, 0x66, 0xdf, 0xa0, 0x65, 0x96, 0xdc, 0x83, 0xad, 0xbc, 0x04, 0xdb, 0x0d, 0xd5,
	0xae, 0x03, 0x12, 0x40, 0x53, 0x16, 0x29, 0xda, 0xcd, 0xbe, 0x31, 0xec, 0x78, 0x6f, 0xae, 0x39,
	0x8c, 0x7a, 0x71, 0x50, 0xa4, 0x48, 0x15, 0x8d, 0x9c, 0x80, 0x85, 0xc9, 0x82, 0x2f, 0xd1, 0xde,
	0x52, 0x5c, 0xff, 0x26, 0xdc, 0x91, 0x22, 0xd1, 0x8a, 0xd8, 0xfb, 0x61, 0x42, 0xb3, 0xb4, 0x8b,
	0x3c, 0x06, 0x4b, 0x37, 0x6b, 0x43, 0x36, 0x07, 0xae, 0x0a, 0x84, 0xc3, 0x1e, 0x4f, 0xc2, 0x4a,
	0x22, 0x15, 0x98, 0x61, 0x22, 0x95, 0x3d, 0x6d, 0xef, 0xe0, 0x9a, 0x4f, 0xda, 0xdc, 0x0f, 0xbd,
	0xcb, 0x93, 0x77, 0xea, 0xf2, 0x4c, 0xb3, 0xff, 0x17, 0x5c, 0x45, 0x59, 0x16, 0x25, 0xe7, 0xca,
	0xf0, 0xdb, 0x16, 0x1c, 0x6b, 0x36, 0x79, 0x00, 0x96, 0xc0, 0x15, 0xcf, 0xf5, 0x06, 0xb7, 0x69,
	0x15, 0x0d, 0x5e, 0x42, 0xeb, 0xdf, 0x52, 0x08, 0x80, 0x75, 0x14, 0xd0, 0xf7, 0x93, 0xc3, 0xee,
	0x9d, 0xf2, 0x3c, 0x99, 0x8f, 0xfd, 0x11, 0xed, 0x1a, 0x84, 0x40, 0x67, 0x46, 0xa7, 0xc1, 0xd4,
	0x9f, 0xbf, 0x0d, 0x8f, 0xf7, 0x3f, 0xce, 0x47, 0x5d, 0x73, 0xf0, 0x04, 0xda, 0x1b, 0xae, 0x93,
	0x6d, 0x68, 0x4e, 0xa6, 0x93, 0x91, 0x6e, 0xf4, 0xf7, 0x8f, 0x46, 0x2f, 0x9e, 0x77, 0x0d, 0xff,
	0x13, 0xbc, 0x8e, 0xb8, 0x9e, 0x27, 0x15, 0xfc, 0x5b, 0x71, 0xc5, 0xd1, 0xfc, 0xfb, 0x7a, 0x88,
	0x80, 0x8f, 0xab, 0xe4, 0xac, 0xfc, 0xd0, 0x33, 0xe3, 0xc4, 0xcc, 0xbd, 0x53, 0x4b, 0xfd, 0xee,
	0x67, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x9b, 0xd7, 0x0b, 0x71, 0x04, 0x00, 0x00,
}
