// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/config/filter/http/fault/v2/fault.proto

package v2

import (
	fmt "fmt"
	route "github.com/envoyproxy/go-control-plane/envoy/api/v2/route"
	v2 "github.com/envoyproxy/go-control-plane/envoy/config/filter/fault/v2"
	_type "github.com/envoyproxy/go-control-plane/envoy/type"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FaultAbort struct {
	// Types that are valid to be assigned to ErrorType:
	//	*FaultAbort_HttpStatus
	ErrorType isFaultAbort_ErrorType `protobuf_oneof:"error_type"`
	// The percentage of requests/operations/connections that will be aborted with the error code
	// provided.
	Percentage           *_type.FractionalPercent `protobuf:"bytes,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *FaultAbort) Reset()         { *m = FaultAbort{} }
func (m *FaultAbort) String() string { return proto.CompactTextString(m) }
func (*FaultAbort) ProtoMessage()    {}
func (*FaultAbort) Descriptor() ([]byte, []int) {
	return fileDescriptor_26070db6b6576d5c, []int{0}
}

func (m *FaultAbort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FaultAbort.Unmarshal(m, b)
}
func (m *FaultAbort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FaultAbort.Marshal(b, m, deterministic)
}
func (m *FaultAbort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaultAbort.Merge(m, src)
}
func (m *FaultAbort) XXX_Size() int {
	return xxx_messageInfo_FaultAbort.Size(m)
}
func (m *FaultAbort) XXX_DiscardUnknown() {
	xxx_messageInfo_FaultAbort.DiscardUnknown(m)
}

var xxx_messageInfo_FaultAbort proto.InternalMessageInfo

type isFaultAbort_ErrorType interface {
	isFaultAbort_ErrorType()
}

type FaultAbort_HttpStatus struct {
	HttpStatus uint32 `protobuf:"varint,2,opt,name=http_status,json=httpStatus,proto3,oneof"`
}

func (*FaultAbort_HttpStatus) isFaultAbort_ErrorType() {}

func (m *FaultAbort) GetErrorType() isFaultAbort_ErrorType {
	if m != nil {
		return m.ErrorType
	}
	return nil
}

func (m *FaultAbort) GetHttpStatus() uint32 {
	if x, ok := m.GetErrorType().(*FaultAbort_HttpStatus); ok {
		return x.HttpStatus
	}
	return 0
}

func (m *FaultAbort) GetPercentage() *_type.FractionalPercent {
	if m != nil {
		return m.Percentage
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FaultAbort) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FaultAbort_HttpStatus)(nil),
	}
}

type HTTPFault struct {
	// If specified, the filter will inject delays based on the values in the
	// object.
	Delay *v2.FaultDelay `protobuf:"bytes,1,opt,name=delay,proto3" json:"delay,omitempty"`
	// If specified, the filter will abort requests based on the values in
	// the object. At least *abort* or *delay* must be specified.
	Abort *FaultAbort `protobuf:"bytes,2,opt,name=abort,proto3" json:"abort,omitempty"`
	// Specifies the name of the (destination) upstream cluster that the
	// filter should match on. Fault injection will be restricted to requests
	// bound to the specific upstream cluster.
	UpstreamCluster string `protobuf:"bytes,3,opt,name=upstream_cluster,json=upstreamCluster,proto3" json:"upstream_cluster,omitempty"`
	// Specifies a set of headers that the filter should match on. The fault
	// injection filter can be applied selectively to requests that match a set of
	// headers specified in the fault filter config. The chances of actual fault
	// injection further depend on the value of the :ref:`percentage
	// <envoy_api_field_config.filter.http.fault.v2.FaultAbort.percentage>` field.
	// The filter will check the request's headers against all the specified
	// headers in the filter config. A match will happen if all the headers in the
	// config are present in the request with the same values (or based on
	// presence if the *value* field is not in the config).
	Headers []*route.HeaderMatcher `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty"`
	// Faults are injected for the specified list of downstream hosts. If this
	// setting is not set, faults are injected for all downstream nodes.
	// Downstream node name is taken from :ref:`the HTTP
	// x-envoy-downstream-service-node
	// <config_http_conn_man_headers_downstream-service-node>` header and compared
	// against downstream_nodes list.
	DownstreamNodes []string `protobuf:"bytes,5,rep,name=downstream_nodes,json=downstreamNodes,proto3" json:"downstream_nodes,omitempty"`
	// The maximum number of faults that can be active at a single time via the configured fault
	// filter. Note that because this setting can be overridden at the route level, it's possible
	// for the number of active faults to be greater than this value (if injected via a different
	// route). If not specified, defaults to unlimited. This setting can be overridden via
	// `runtime <config_http_filters_fault_injection_runtime>` and any faults that are not injected
	// due to overflow will be indicated via the `faults_overflow
	// <config_http_filters_fault_injection_stats>` stat.
	//
	// .. attention::
	//   Like other :ref:`circuit breakers <arch_overview_circuit_break>` in Envoy, this is a fuzzy
	//   limit. It's possible for the number of active faults to rise slightly above the configured
	//   amount due to the implementation details.
	MaxActiveFaults *wrappers.UInt32Value `protobuf:"bytes,6,opt,name=max_active_faults,json=maxActiveFaults,proto3" json:"max_active_faults,omitempty"`
	// The response rate limit to be applied to the response body of the stream. When configured,
	// the percentage can be overridden by the :ref:`fault.http.rate_limit.response_percent
	// <config_http_filters_fault_injection_runtime>` runtime key.
	//
	// .. attention::
	//  This is a per-stream limit versus a connection level limit. This means that concurrent streams
	//  will each get an independent limit.
	ResponseRateLimit *v2.FaultRateLimit `protobuf:"bytes,7,opt,name=response_rate_limit,json=responseRateLimit,proto3" json:"response_rate_limit,omitempty"`
	// The runtime key to override the :ref:`default <config_http_filters_fault_injection_runtime>`
	// runtime. The default is: fault.http.delay.fixed_delay_percent
	DelayPercentRuntime string `protobuf:"bytes,8,opt,name=delay_percent_runtime,json=delayPercentRuntime,proto3" json:"delay_percent_runtime,omitempty"`
	// The runtime key to override the :ref:`default <config_http_filters_fault_injection_runtime>`
	// runtime. The default is: fault.http.abort.abort_percent
	AbortPercentRuntime string `protobuf:"bytes,9,opt,name=abort_percent_runtime,json=abortPercentRuntime,proto3" json:"abort_percent_runtime,omitempty"`
	// The runtime key to override the :ref:`default <config_http_filters_fault_injection_runtime>`
	// runtime. The default is: fault.http.delay.fixed_duration_ms
	DelayDurationRuntime string `protobuf:"bytes,10,opt,name=delay_duration_runtime,json=delayDurationRuntime,proto3" json:"delay_duration_runtime,omitempty"`
	// The runtime key to override the :ref:`default <config_http_filters_fault_injection_runtime>`
	// runtime. The default is: fault.http.abort.http_status
	AbortHttpStatusRuntime string `protobuf:"bytes,11,opt,name=abort_http_status_runtime,json=abortHttpStatusRuntime,proto3" json:"abort_http_status_runtime,omitempty"`
	// The runtime key to override the :ref:`default <config_http_filters_fault_injection_runtime>`
	// runtime. The default is: fault.http.max_active_faults
	MaxActiveFaultsRuntime string `protobuf:"bytes,12,opt,name=max_active_faults_runtime,json=maxActiveFaultsRuntime,proto3" json:"max_active_faults_runtime,omitempty"`
	// The runtime key to override the :ref:`default <config_http_filters_fault_injection_runtime>`
	// runtime. The default is: fault.http.rate_limit.response_percent
	ResponseRateLimitPercentRuntime string   `protobuf:"bytes,13,opt,name=response_rate_limit_percent_runtime,json=responseRateLimitPercentRuntime,proto3" json:"response_rate_limit_percent_runtime,omitempty"`
	XXX_NoUnkeyedLiteral            struct{} `json:"-"`
	XXX_unrecognized                []byte   `json:"-"`
	XXX_sizecache                   int32    `json:"-"`
}

func (m *HTTPFault) Reset()         { *m = HTTPFault{} }
func (m *HTTPFault) String() string { return proto.CompactTextString(m) }
func (*HTTPFault) ProtoMessage()    {}
func (*HTTPFault) Descriptor() ([]byte, []int) {
	return fileDescriptor_26070db6b6576d5c, []int{1}
}

func (m *HTTPFault) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPFault.Unmarshal(m, b)
}
func (m *HTTPFault) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPFault.Marshal(b, m, deterministic)
}
func (m *HTTPFault) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPFault.Merge(m, src)
}
func (m *HTTPFault) XXX_Size() int {
	return xxx_messageInfo_HTTPFault.Size(m)
}
func (m *HTTPFault) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPFault.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPFault proto.InternalMessageInfo

func (m *HTTPFault) GetDelay() *v2.FaultDelay {
	if m != nil {
		return m.Delay
	}
	return nil
}

func (m *HTTPFault) GetAbort() *FaultAbort {
	if m != nil {
		return m.Abort
	}
	return nil
}

func (m *HTTPFault) GetUpstreamCluster() string {
	if m != nil {
		return m.UpstreamCluster
	}
	return ""
}

func (m *HTTPFault) GetHeaders() []*route.HeaderMatcher {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *HTTPFault) GetDownstreamNodes() []string {
	if m != nil {
		return m.DownstreamNodes
	}
	return nil
}

func (m *HTTPFault) GetMaxActiveFaults() *wrappers.UInt32Value {
	if m != nil {
		return m.MaxActiveFaults
	}
	return nil
}

func (m *HTTPFault) GetResponseRateLimit() *v2.FaultRateLimit {
	if m != nil {
		return m.ResponseRateLimit
	}
	return nil
}

func (m *HTTPFault) GetDelayPercentRuntime() string {
	if m != nil {
		return m.DelayPercentRuntime
	}
	return ""
}

func (m *HTTPFault) GetAbortPercentRuntime() string {
	if m != nil {
		return m.AbortPercentRuntime
	}
	return ""
}

func (m *HTTPFault) GetDelayDurationRuntime() string {
	if m != nil {
		return m.DelayDurationRuntime
	}
	return ""
}

func (m *HTTPFault) GetAbortHttpStatusRuntime() string {
	if m != nil {
		return m.AbortHttpStatusRuntime
	}
	return ""
}

func (m *HTTPFault) GetMaxActiveFaultsRuntime() string {
	if m != nil {
		return m.MaxActiveFaultsRuntime
	}
	return ""
}

func (m *HTTPFault) GetResponseRateLimitPercentRuntime() string {
	if m != nil {
		return m.ResponseRateLimitPercentRuntime
	}
	return ""
}

func init() {
	proto.RegisterType((*FaultAbort)(nil), "envoy.config.filter.http.fault.v2.FaultAbort")
	proto.RegisterType((*HTTPFault)(nil), "envoy.config.filter.http.fault.v2.HTTPFault")
}

func init() {
	proto.RegisterFile("envoy/config/filter/http/fault/v2/fault.proto", fileDescriptor_26070db6b6576d5c)
}

var fileDescriptor_26070db6b6576d5c = []byte{
	// 638 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xc1, 0x6e, 0xd3, 0x4e,
	0x10, 0xc6, 0xff, 0x6e, 0x9a, 0xb4, 0xdd, 0xfc, 0xab, 0xb6, 0x2e, 0x14, 0x53, 0x41, 0x49, 0xcb,
	0xc5, 0x20, 0xba, 0x46, 0x2e, 0x17, 0x84, 0x40, 0x6a, 0x52, 0x55, 0x01, 0x15, 0x14, 0x99, 0xc2,
	0x01, 0x21, 0x59, 0x9b, 0x78, 0x92, 0x58, 0x72, 0xbc, 0xd6, 0x7a, 0xed, 0x26, 0x6f, 0xc2, 0x4b,
	0x70, 0x47, 0x9c, 0x7a, 0xe4, 0x11, 0x78, 0x85, 0xbe, 0x05, 0xda, 0x59, 0x3b, 0x0d, 0x4d, 0xa4,
	0x72, 0xa9, 0xdc, 0x9d, 0xef, 0x37, 0xb3, 0xf3, 0xed, 0x17, 0x72, 0x08, 0x71, 0xce, 0x27, 0x4e,
	0x8f, 0xc7, 0xfd, 0x70, 0xe0, 0xf4, 0xc3, 0x48, 0x82, 0x70, 0x86, 0x52, 0x26, 0x4e, 0x9f, 0x65,
	0x91, 0x74, 0x72, 0x57, 0x7f, 0xd0, 0x44, 0x70, 0xc9, 0xcd, 0x7d, 0x94, 0x53, 0x2d, 0xa7, 0x5a,
	0x4e, 0x95, 0x9c, 0x6a, 0x55, 0xee, 0xee, 0xee, 0xe9, 0x8e, 0x2c, 0x09, 0x15, 0x2c, 0x78, 0x26,
	0x41, 0xff, 0xd5, 0x2d, 0x76, 0xed, 0x45, 0x13, 0x17, 0x0d, 0xdb, 0xb5, 0xb4, 0x52, 0x4e, 0x12,
	0x70, 0x12, 0x10, 0x3d, 0x88, 0xcb, 0xca, 0xde, 0x80, 0xf3, 0x41, 0x04, 0x0e, 0xfe, 0xd7, 0xcd,
	0xfa, 0xce, 0x85, 0x60, 0x49, 0x02, 0x22, 0x2d, 0xea, 0xf7, 0x72, 0x16, 0x85, 0x01, 0x93, 0xe0,
	0x94, 0x1f, 0xba, 0x70, 0xf0, 0xcd, 0x20, 0xe4, 0x54, 0x8d, 0x38, 0xee, 0x72, 0x21, 0xcd, 0xe7,
	0xa4, 0xae, 0x2e, 0xef, 0xa7, 0x92, 0xc9, 0x2c, 0xb5, 0x96, 0x1a, 0x86, 0xbd, 0xde, 0x5c, 0xff,
	0x79, 0x75, 0x59, 0x59, 0x7d, 0x5a, 0xdb, 0xfc, 0xbd, 0x6c, 0xff, 0x32, 0xda, 0xff, 0x79, 0x44,
	0x69, 0x3e, 0xa2, 0xc4, 0x7c, 0x4d, 0x48, 0x71, 0x15, 0x36, 0x00, 0xab, 0xd2, 0x30, 0xec, 0xba,
	0xfb, 0x90, 0x6a, 0x57, 0xd4, 0x45, 0xe9, 0xa9, 0x60, 0x3d, 0x19, 0xf2, 0x98, 0x45, 0x1d, 0xad,
	0xf3, 0x66, 0x80, 0xe6, 0x36, 0x21, 0x20, 0x04, 0x17, 0xbe, 0xd2, 0x9a, 0xd5, 0x1f, 0x57, 0x97,
	0x15, 0xe3, 0xdd, 0xf2, 0xaa, 0xb1, 0xb9, 0x74, 0xf0, 0xbd, 0x46, 0xd6, 0xda, 0xe7, 0xe7, 0x1d,
	0xbc, 0x9e, 0xf9, 0x86, 0x54, 0x03, 0x88, 0xd8, 0xc4, 0x32, 0x70, 0x84, 0x4d, 0x17, 0x19, 0x5f,
	0x7a, 0x4e, 0x91, 0x39, 0x51, 0x7a, 0x4f, 0x63, 0x66, 0x8b, 0x54, 0x99, 0x5a, 0x11, 0x77, 0xaa,
	0xbb, 0x87, 0xf4, 0xd6, 0x87, 0xa3, 0xd7, 0xbe, 0x78, 0x9a, 0x35, 0x9f, 0x90, 0xcd, 0x2c, 0x49,
	0xa5, 0x00, 0x36, 0xf2, 0x7b, 0x51, 0x96, 0x4a, 0x10, 0xb8, 0xf2, 0x9a, 0xb7, 0x51, 0x9e, 0xb7,
	0xf4, 0xb1, 0xf9, 0x8a, 0xac, 0x0c, 0x81, 0x05, 0x20, 0x52, 0x6b, 0xb9, 0x51, 0xb1, 0xeb, 0xee,
	0x7e, 0x31, 0x91, 0x25, 0xa1, 0x6a, 0xae, 0x13, 0xd0, 0x46, 0xc9, 0x7b, 0x26, 0x7b, 0x43, 0x10,
	0x5e, 0x49, 0xa8, 0x39, 0x01, 0xbf, 0x88, 0x8b, 0x49, 0x31, 0x0f, 0x20, 0xb5, 0xaa, 0x8d, 0x8a,
	0x9a, 0x73, 0x7d, 0xfe, 0x41, 0x1d, 0x9b, 0x6d, 0xb2, 0x35, 0x62, 0x63, 0x5f, 0x79, 0x9c, 0x83,
	0x8f, 0x77, 0x4f, 0xad, 0x1a, 0xee, 0xf8, 0x80, 0xea, 0x54, 0xd0, 0x32, 0x15, 0xf4, 0xd3, 0xdb,
	0x58, 0x1e, 0xb9, 0x9f, 0x59, 0x94, 0x81, 0xb7, 0x31, 0x62, 0xe3, 0x63, 0xa4, 0x70, 0xcf, 0xd4,
	0xfc, 0x4a, 0xb6, 0x05, 0xa4, 0x09, 0x8f, 0x53, 0xf0, 0x05, 0x93, 0xe0, 0x47, 0xe1, 0x28, 0x94,
	0xd6, 0x0a, 0xf6, 0x7a, 0xf6, 0x0f, 0x7e, 0x7b, 0x4c, 0xc2, 0x99, 0x62, 0xbc, 0xad, 0xb2, 0xd1,
	0xf4, 0xc8, 0x74, 0xc9, 0x5d, 0x7c, 0x08, 0xbf, 0x78, 0x7c, 0x5f, 0x64, 0xb1, 0x0c, 0x47, 0x60,
	0xad, 0xa2, 0x7f, 0xdb, 0x58, 0x2c, 0x13, 0xa2, 0x4b, 0x8a, 0x41, 0xdf, 0xe7, 0x98, 0x35, 0xcd,
	0x60, 0xf1, 0x06, 0xf3, 0x82, 0xec, 0xe8, 0x39, 0x41, 0x26, 0x98, 0xca, 0xdd, 0x14, 0x22, 0x08,
	0xdd, 0xc1, 0xea, 0x49, 0x51, 0x2c, 0xa9, 0x97, 0xe4, 0xbe, 0x9e, 0x34, 0x93, 0xfe, 0x29, 0x58,
	0x47, 0x70, 0x07, 0x05, 0xed, 0x69, 0xf2, 0x67, 0xd0, 0xb9, 0x07, 0x98, 0xa2, 0xff, 0x6b, 0xf4,
	0x86, 0xd5, 0x25, 0x7a, 0x46, 0x1e, 0x2f, 0x70, 0x7c, 0x6e, 0xdb, 0x75, 0x6c, 0xf2, 0x68, 0xce,
	0xd3, 0xbf, 0x37, 0x6f, 0xb6, 0x88, 0x13, 0x72, 0xfd, 0x4c, 0x89, 0xe0, 0xe3, 0xc9, 0xed, 0x09,
	0x6f, 0xea, 0x9f, 0x7e, 0x47, 0xc5, 0xa3, 0x63, 0x7c, 0x59, 0xca, 0xdd, 0x6e, 0x0d, 0xb3, 0x72,
	0xf4, 0x27, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x99, 0xa2, 0xba, 0x07, 0x05, 0x00, 0x00,
}
